# Практическая работа 4. Advanced RAG

В ноутбуке исследуется влияние reranking и параметров гибридного поиска на качество RAG-системы.

В рамках работы:
- сравниваются две Cross-Encoder модели для reranking;
- анализируется влияние reranker на порядок документов и итоговые ответы;
- настраиваются веса semantic search и BM25;
- сравниваются разные embedding-модели и значения `k`;
- измеряются скорость retrieval, reranking и генерации;
- выбирается конфигурация с оптимальным балансом качества и скорости.

## Задание 1

В первом задании сравниваются две Cross-Encoder модели на одинаковых запросах: анализируется порядок документов после reranking и качество итоговых ответов.

In [1]:
!pip install -q \
    "langchain>=0.3.0" \
    "langchain-openai>=0.2.0" \
    "langchain-community>=0.3.0" \
    "langchain-core>=0.3.0" \
    "langchain-text-splitters>=0.3.0" \
    "pypdf>=5.0.0" \
    "sentence-transformers>=3.0.0" \
    "rank-bm25"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.1/572.1 kB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 23.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [2]:
import asyncio
import time
import numpy as np
import pandas as pd

from pathlib import Path
from typing import List

from google.colab import userdata

from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import InMemoryVectorStore
from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers import EnsembleRetriever

from langchain_core.embeddings import Embeddings
from langchain_core.messages import HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

from sentence_transformers import SentenceTransformer, CrossEncoder

/tmp/ipykernel_995/3512822923.py:12: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

In [3]:
OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

OPENROUTER_MODEL = "cohere/north-mini-code:free"

_llm = ChatOpenAI(
    api_key=OPENROUTER_API_KEY,
    model=OPENROUTER_MODEL,
    base_url="https://openrouter.ai/api/v1",
    temperature=0,
)

Загрузка PDF и embeddings:

In [4]:
class HFEmbeddings(Embeddings):
    def __init__(
        self,
        model_name="intfloat/multilingual-e5-base",
        device="cpu",
    ):
        self.model = SentenceTransformer(
            model_name,
            device=device,
        )

    def embed_documents(self, texts: List[str]):
        embeddings = self.model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True,
        )
        return embeddings.tolist()

    def embed_query(self, text: str):
        embedding = self.model.encode(
            [text],
            convert_to_numpy=True,
            normalize_embeddings=True,
        )[0]
        return embedding.tolist()

In [5]:
def load_pdf_documents(data_dir):
    pages = []

    for pdf_file in Path(data_dir).glob("*.pdf"):
        loader = PyPDFLoader(str(pdf_file))
        pages.extend(loader.load())

    return pages


def split_documents(pages):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=150,
    )

    return splitter.split_documents(pages)

Загрузка и индексация документов:

In [6]:
DATA_DIR = "/content/docs"

pages = load_pdf_documents(DATA_DIR)
chunks = split_documents(pages)

print("Pages:", len(pages))
print("Chunks:", len(chunks))

Pages: 61
Chunks: 254

Эмбеддинги и vector store:

In [7]:
embeddings = HFEmbeddings(
    model_name="intfloat/multilingual-e5-base",
    device="cpu",
)

vectorstore = InMemoryVectorStore(embeddings)
vectorstore.add_documents(chunks)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/179k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

['3b54929e-9c4a-4b08-b40f-88b7a6f60633',
 '4c4a274d-de68-40fe-a19c-e597bf3acf19',
 'd1bef611-f034-41a1-b776-f4987bda86fe',
 '4c012916-0a1c-43c8-be23-39fe0a6cce63',
 'a2d8d9df-8c94-4f8d-97b2-5f3e5cb00259',
 '91cc115e-817c-4d5c-99fb-ef280b8f5f2a',
 '09c569e6-8e8f-4546-8445-763c0cfa651e',
 'd46813fe-d6d6-4cc8-a2e0-e6dc8348cc0f',
 'e50f3a56-9b6d-4149-b3be-65d746f9d614',
 '569f7d55-1544-4409-8223-57ba73ad2651',
 '7af58dd3-f8ce-426f-b8fa-28df1632a236',
 '8a6d177d-b21c-4fc8-90a0-4ce7f5906b4c',
 'c0d757fd-b442-47db-8c2a-60cacccc48b8',
 '5e037e75-3846-44c7-9c62-ef6b3ba1943f',
 '483dfe1a-1061-46c1-bdba-340de5f545f9',
 '8e21883f-61ff-4661-9a94-64a027e3a342',
 'a32f7502-04dc-4b65-b23f-3690902282b9',
 'ab6ca3c5-d137-48c0-a5e3-29c1d2a51ed2',
 '30953ae3-b477-4ad1-aad9-6cf796d07713',
 '9f468d8f-23b7-4e07-99c0-a9eab194d8fd',
 'eb6d353b-0b61-4948-b951-8ce36edaaa7c',
 'ffa23ded-5014-45b3-82f2-a5a30d1e4eef',
 '4502ed3b-e506-46b2-8f56-6726c94aecc8',
 '6bce932c-f285-466c-b8f3-55999e20247a',
 '173da5c5-de20-4ff7-b081-8adf6842f63c',
 '40b00474-036a-47db-8b6c-3a3bb8c28436',
 '9ca2ab49-7757-425e-ba21-51edad3f2e60',
 'e1878115-0ca9-43a2-8c76-4399ffa40d7d',
 '11698413-9759-4d8e-9bc0-d6692b9048a1',
 'a9ee87b8-c411-440b-b58c-3585a8f857c1',
 'a8bb2ce8-6390-49d6-a59e-b4e614661f54',
 '7e268c4f-b2bf-47c6-b069-d906a3931d56',
 'b41b3ae2-3ada-4224-8844-95d9364f7080',
 'e243c9ff-6994-4a83-900c-f22cc4fc2e19',
 '71bff694-aaff-4a3f-a574-42fc8fb147ff',
 '5dfcf4a6-3424-4541-a616-4456bf9fa4cb',
 '8bc4de2f-60fc-4e43-990e-99f2f2209a58',
 'a2443b77-3ba1-4703-92a1-c094de8b1592',
 'cb503c67-f59f-420e-b9ec-9522314c016e',
 'ef8b2eb6-daad-4a60-b142-6be315f4551c',
 'ca0f3008-60d6-4674-940c-a823eedae6d7',
 '98d09a63-f788-410a-94dd-792f79295036',
 'b5978ad6-d522-4292-a6ab-9385f7b9f2bd',
 'c53bb426-47c2-40ab-b9a2-08426c2cb611',
 '06b1ba3a-a0f8-48bc-ae5e-ccd4f0f450eb',
 '6f27671c-3140-4128-9ecb-c5dceeec333c',
 'cec0b8f2-6dfd-4e54-b730-29a3516e41b8',
 'c956cd73-0aa4-4d4a-af07-9ed9ff4936bb',
 '4fbefcbc-ae5a-4964-a7a0-99b4afcfe134',
 'd261cce3-5517-437a-b9fc-105be366f0a4',
 'fbad4242-0afa-45f3-a317-453dd0f3021f',
 '948d69e7-5cfe-44e3-badb-7dbd4dda7e9d',
 'ea4a74a6-0a9b-41d0-91d9-95291c67de58',
 '762e9233-670d-4ef8-bd6f-eae5de79fb09',
 '91ef5a3d-c242-4dee-81e1-11f8b07a202c',
 'a9604b95-82b8-4424-a5c4-ebc554d9c8b9',
 '78168194-8ad5-414d-85e9-224277ee10c5',
 '4a20d918-d4eb-4145-a752-2405e121eb61',
 '1724c6d4-42ac-4bab-9cc8-581f37f56ba1',
 '21ebad3a-fe56-4941-9efa-4752ecbae094',
 '339af22a-544f-4620-831f-ccdba71e3d89',
 'cac98213-aa4c-4e50-a21f-69c9132794c8',
 'aefbc446-7b14-4bdb-939f-9067e7098f79',
 '8ad50031-cd8d-46b9-98ba-a911bd259002',
 'ec78ff65-0295-40f2-98cf-4a040db252a1',
 'ae92171a-04fd-4c40-b8cf-4bd0145059d6',
 '19b5de3e-3234-47f4-b348-6f7b47bdfbaa',
 'f90788bc-2a45-4246-8e71-bd7b97c84220',
 '779f039e-0388-4c15-a1b6-24f5dafc2f74',
 '15735e3f-2a6a-4e76-a2d2-27cd455119aa',
 '7e6dc823-4d0f-4432-a22d-0d9c6d51728d',
 'd0906156-a229-4624-ad3a-db194095935d',
 '04fdd2ce-4551-4d7e-9fc3-a2caf83c3efb',
 'b8252836-2821-4db3-bba9-7a032c6a6267',
 '800e122a-72d1-4919-a504-ad72161e468a',
 'c53d8903-46ea-4adf-8db8-f6212f510331',
 'f8da33e0-9402-457a-b246-899a9cc67137',
 '96be080e-1b7a-41ba-a35c-343cbeef8fbe',
 'e6236809-9db2-4ab8-ad21-ffd726858489',
 '296fd06d-0adb-4075-857c-da795ece7a71',
 '40718262-9456-4118-a9a6-08668ca0e7f3',
 '39509027-a964-44a3-9c99-30fe42f86eb0',
 '403c4329-cf98-4f3f-851e-d4643351195e',
 '80104ccc-d14c-42b9-9169-a52a920288b9',
 '7f86ba72-6474-4cca-8fd9-1d0b6d913ddb',
 '870a072d-57a5-4527-b6c3-4254ba6b8c8b',
 '700cd5d1-0989-4f46-919f-8f35b2fe600c',
 '7f9268c3-803b-454a-ae54-0895f7d17a3a',
 'b02ecbfe-3a50-4e19-9668-8b1b75781325',
 'c162a4c0-d07c-4cef-a015-8a9af09ad920',
 'cd5e8203-72ef-4de4-a5f0-d129be37cd1c',
 'ad57046c-5422-4c54-8c5b-9c1a2e39e905',
 '433bf107-3f44-4c6b-8b6f-d72c29415353',
 'c7fff59b-fa12-40fe-a4ad-497e12ddc0bb',
 '1ce6fb71-8037-43a6-b7f8-966b062d00e7',
 '8b8debd1-dcef-4e1d-a69b-06b3e7e70f2f',
 '3e1b333b-b630-4af6-ad04-c5a9250df6c3',
 '02e7af73-7207-4948-8bb5-32ac31f35943',
 '91fa360b-1954-4929-a321-b1bfdce82132',
 'bfe62e05-a0da-433b-8292-d1f2fda6017f',
 '945968d9-c7ff-4948-ade2-68b17ea4f7e1',
 '06097e7e-ca9a-405b-ba8c-d590774c20c4',
 '15f0ccf9-3ed0-44fa-a07c-4b2b0aeab52b',
 '3a07cca2-5745-471d-9125-a346f19844ba',
 '26512c60-8587-4bbf-b039-a291c3e8a93d',
 'f7256b79-d920-46e8-a85a-ae7c749f9584',
 '4bcaf372-77a5-46c5-a848-b02363d39439',
 '6695f0c7-437f-4547-b111-cd69b049914c',
 '0148ff5b-1f09-456c-baae-8060e5812656',
 '74f9ce6d-d064-4a84-bcf8-9d1982323866',
 '59910b0a-38fb-4293-917a-389af5c52265',
 '597fc086-0c10-4e77-97b6-e9a3e4830961',
 '204caac0-98f9-4336-a53c-ad51c1ac2eb4',
 '48ebffc1-d629-42aa-aaf9-3a7c3d05052a',
 'e8684470-28f8-4b59-8be6-982e55fb87ac',
 'c175e85b-fe52-401d-80f6-06bf976770d5',
 '4ebecca8-12bb-467e-af15-b26f9ade23d9',
 'efeefe3f-18a7-4c29-b4ea-cc69c26b5055',
 '4b679d33-1729-43e3-a4a8-c80c574a1476',
 '6d4c01c4-2fc1-470d-be2d-0ac3f8d2a14c',
 '82fa4dd3-d868-43e5-9cef-d96c264cdf33',
 '2ffc6284-5989-463b-8b2b-4e1b60e8ca37',
 'e059a68b-0e46-486c-a434-9e8521e5703f',
 'e529eab8-6bfc-4e02-b6d9-9861555efb50',
 'aa27b73d-5b1d-491e-9d27-08a3734aecec',
 '1a9e9372-92bf-45ff-921e-5737c7aa6a79',
 '1b201561-19ce-4439-84a8-b73a747d0b34',
 'e0a7d22b-30e0-4fdf-adc8-31c8b8430371',
 '4765444f-5ffa-4aa6-a595-d121fe08d1c3',
 '52e4e70a-4c48-4072-b578-20a80b99d3dc',
 'e0e19c47-d9bf-475f-bc33-d5de94bcca2a',
 '3c53584e-fe6c-460d-a226-da7260bb4ee1',
 '65a9a644-a8b5-46e2-92e0-d0525835ab1b',
 '6f3f247c-4f4d-4339-ad02-69a9fed146fa',
 '1dfc1d34-77d8-4068-85e7-6d581e96ab16',
 '374e0974-4c3f-4514-b31e-fb4d79c55934',
 '79c601ee-2717-48d4-81bf-c9b701b0bcb4',
 'e89f4fff-3bf1-4b84-a441-9a22e0949e54',
 '0a006dbe-62a6-4d2d-91da-9704c895da99',
 'fe027eea-ee35-448a-80ec-bc044b05246c',
 '8740226f-e02a-4f4e-b40d-d62c6b05866a',
 'e957f931-7c69-4cd0-9621-28fbfc696ca4',
 'ccf513c9-38c0-480a-9ed3-32867216ec8c',
 '19595ae6-dcca-45d3-829d-7c61794aee2e',
 '150f21dc-6c17-4d9d-9c08-5326e2bf49d7',
 '6b3673af-deb9-4d61-947e-fe5665f52ec1',
 'd7676185-0f25-425e-b43e-c7ae8434b51c',
 '5c0ceba2-38af-46be-9d5a-733d48b68683',
 'ee8c2c30-7e7c-4398-b61c-11537f50a238',
 '89c4aa71-07a5-4e82-aa2c-87fedc3fb979',
 'c979907b-0432-455d-9fe1-d47f5b38d0d2',
 '2dbf4e44-833a-4051-b4ab-f407a6c92ec4',
 'fd828bdf-c321-4339-8bae-8d34d7a8f375',
 '63fbbda8-4a49-4290-a262-2960be5e6308',
 '09d4d638-1d69-44df-ab37-207f4706e940',
 '3bab4c05-19ac-43cc-9c6d-cba7baa675d6',
 'fb45f23b-5fa1-41a5-91ae-5a0bb8d72176',
 '4563f8ff-95f3-4a84-89c1-0fad2ff2c2f8',
 'b13c9104-3613-47a6-b54f-85a7937ab01c',
 'ba758973-5538-4291-92f1-43bc7b975b8a',
 '21d4aa9d-624d-4c46-9d46-684604916830',
 'e1e3d919-71cd-4e9d-b846-c33f192abc03',
 '331a6156-ed48-47d4-9c5d-ff38a7aaca62',
 '0cb4a3d5-000c-4100-a8f1-320a0e15d337',
 '5112d42a-cb30-4741-9395-fca45345a078',
 'd15526a3-c33e-475f-87af-9ca4429bf452',
 '7f24526f-893a-4114-9886-49c9e7490cdb',
 '1f0e8031-9d80-4bd3-a1e7-2998702bb161',
 'e2f53d84-3fb4-4205-8255-308dc5beb6eb',
 '0d177572-5ad3-4bd7-aee6-f79db92c3675',
 '6d35ab2d-03df-4e6f-b849-76cebaf943a5',
 'ba861a08-b253-4c63-b068-3c4b4125c116',
 'c10b0068-64e1-4945-aab2-b28d43158359',
 '48afbea3-9341-4a87-8d53-ee21d8339beb',
 '9b26d886-b7b2-4d18-9b3b-0162c5da27c2',
 'de3e0dcb-a663-45e0-b56c-3acc4499829c',
 '3ab74877-d89c-4cdc-884b-0d80bb955b15',
 '48a62624-835d-4842-b2e3-f4ccaee58534',
 '55a3ea28-4810-403c-a8af-9c05d2e80acc',
 'e9f82ac8-0616-40eb-a3d9-53b85094f9bd',
 'eac3dd9a-7cd7-4bb4-88a8-7468f9125660',
 '61d969ac-cf8c-400e-8f5c-76cc37f576da',
 '4ee17e5c-4c22-453e-b538-0654c52b44ee',
 '410bb70a-56f8-40c9-a04c-31ab947cfbd8',
 '5390995b-cdff-4c2f-843d-24f08d544721',
 '89da49b6-7e00-40bf-8e45-f50973bcba81',
 'bab45a71-ec48-4901-ad4b-8fb99f0e38ae',
 '88923716-756e-4fff-b00f-d5521e268eff',
 '3d681e17-5167-4bf5-ae58-2b3bb7e3451a',
 '4b613249-3ff0-4756-a697-e63114015ddb',
 '927f45d9-5503-4709-855e-bcab8978338a',
 '08b875d1-2672-4033-bc0e-f34e11c74a1f',
 'e834b7a9-796e-40ab-ba42-bfd670f1ca64',
 'a71c00d1-57b6-4677-8cd8-9d71facdee2e',
 '4c692e1b-dd98-4dd1-89a2-6d0098a55d07',
 '3d0e902a-cad2-4867-916d-d864c79595a8',
 '2dd59988-0140-4978-a034-1c8c50e4bafb',
 '3f5b4fa4-39a7-47aa-adc6-bd8f9f68fce9',
 '1231afb6-b32b-4e9e-9770-5a1e92887329',
 '3e81da6c-42b9-4a12-9c5f-637a4a392fb0',
 '5bd717f7-fa54-425e-9bf7-147464be89ec',
 '49a9cee8-c351-46bc-bded-6c59eae05279',
 '955d6db0-a5a6-48c7-8dc5-75ac95766746',
 '11c7a537-6f8a-41a8-b0e6-6dafef7e98af',
 '5133ce9e-f7e3-4d85-9555-fa383ae9e44f',
 'c3b78fb4-4be6-421b-8d8f-695f03e70e7c',
 '71ab5f32-b079-4d81-98b6-1f2734629bde',
 '874b6004-0c64-4a53-a1c6-4543e4e98260',
 'ea9f5c69-209a-4cb8-8301-e8fe2bc768a6',
 '64df9f58-8960-4d18-b7e3-d1618a04c7fb',
 '7ba18738-2e26-4a64-87cb-41ff4b5fd0e1',
 '57294b84-c522-4ca8-93c1-c46cfa952c5c',
 '252673b9-ac32-4d2d-a15e-2cc5148b20b5',
 '7b11a996-4a92-44bb-aca9-105c5e2f6e13',
 'ec7d184c-a63f-4892-b6ca-bec2bd297f7f',
 'd52f98fc-186a-4ba7-98a1-5395c6c3c0d0',
 'feca125d-649c-40fc-8f1a-8186cf9fd89a',
 'eab31a45-abb1-4a89-b2bf-634897a91fbe',
 '2609c456-04a3-4979-8177-101acae3cc89',
 '4c56e438-6022-4d8f-8492-318a7426c398',
 '11177486-1da5-4eb6-81a7-607d3902fec7',
 '7ce219f5-3f14-4b0b-ae53-34c666c3f390',
 '24722e9d-0e34-468d-bb60-7a094b5e2bba',
 '1211ae10-b0de-4f8d-b7db-b26aaa447597',
 '024c330c-db79-45c7-bf40-8201a45c9bb5',
 '488b3fa3-8786-446d-9e5a-7c163cdf1639',
 '270ed81d-c50d-4a8c-b213-1f29ca512bbd',
 '1e5deae8-eab7-431f-80e7-5ae0cc637769',
 'c251606f-08e9-4118-bab0-721d62d704ed',
 '17d0584f-6b55-4b73-850a-310f5991a446',
 '772d61ff-4657-468c-b1eb-993918ffcc91',
 '4a7c4da7-f550-4467-b83c-31ad74e034fb',
 'bcbe8e35-3bfc-4f85-b258-9b0a78ee8707',
 '94d97169-e233-4552-90c2-d887ab3e3984',
 'e9b9b9b8-a86c-4edf-ae0f-8617d362ac9c',
 '802977e2-f342-4781-97e7-401769c27878',
 '96acdd7f-784a-45e9-a103-51f848a346a0',
 'b78810d5-c019-4125-b1fb-6e1727e402c2',
 '8c2485ea-46dd-4742-bedf-15ac8941a139',
 '5a959e21-35b9-4410-8740-54599b88d3dd',
 '7ac9a8f4-e0bb-4078-af15-1f2a5d056f7d',
 '85a4a7d2-6f87-4345-8c0e-2c7efbe05e83',
 'a3af7a08-a922-4e0c-9b28-fbff9320d69a',
 'acbc27e4-af56-4875-bc95-270f1b8676fa',
 'ef0b39b3-9ab4-4c5d-b87f-03f0cf57b993',
 'bc3f2e78-e157-46e6-9028-91fc66fbfa3f',
 'ad2d3228-5ec9-447e-8779-0f1a222ed3e7',
 '4aa8f603-60a0-40a7-9922-04cbd9571b5c',
 'f23fce07-a65e-46b4-aeb8-d9dae5f0a9db',
 'd82b65a8-4499-4203-9d61-5896498bec6c',
 'cf80b445-aec4-4fc4-ad9b-53adc67cc6b1',
 '882e23cf-3679-4226-beeb-3c194c43006f',
 '15d839bd-920c-4df7-8a73-e8648785561d',
 'b3122423-db5c-4807-8a95-7efedd005d45']

In [9]:
# семантический ретривер
semantic_retriever = vectorstore.as_retriever(search_kwargs={"k": 10})

# bm25
bm25_retriever = BM25Retriever.from_documents(chunks)
bm25_retriever.k = 10

# hybrid retriever
hybrid_retriever = EnsembleRetriever(
    retrievers=[
        semantic_retriever,
        bm25_retriever,
    ],
    weights=[0.5, 0.5],
)

In [10]:
# проверим, что ретривер работает

test_query = "What are the main characteristics of chronic poverty?"

retrieved_docs = hybrid_retriever.invoke(test_query)

print("Retrieved:", len(retrieved_docs))

for i, doc in enumerate(retrieved_docs[:5], start=1):
    print("\n" + "=" * 80)
    print("DOC", i)
    print(doc.page_content[:500])

Retrieved: 16

================================================================================
DOC 1
by measures of deficits in current consumption and expenditure. It will be important for
CPRC researchers to engage with these issues of vulnerability, both in terms of
differential vulnerabilities to shocks leading to spells of poverty, as well the manner in
which vulnerability interacts with risk aversion to hinder escape from poverty, through,
for example, adverse incorporation (Wood 2000).6
3 What are the characteristics of chronic poverty?
The defining feature of ‘chronic poverty’ is its ex

================================================================================
DOC 2
3
Table of contents
Title page and acknowledgements 1
Abstract 2
Table of contents 3
List of figures and list of tables 4
Abbreviations 4
1 Background 5
2 Frameworks for understanding and measuring poverty 6
2.1 Material poverty, money-metric measurement approaches and multi-
dimensional concepts of poverty
6
2.2 Absolute and relative poverty 8
2.3 Subjective poverty assessments 8
2.4 Capabilities and freedoms 9
2.5 Vulnerability 9
3 What are the characteristics of chronic poverty? 10
3.1 Durati

================================================================================
DOC 3
7
Poverty based on adverse
incorporation – the
‘productive poor, e.g.
bonded, indentured labour
Figure 1: Chronic poverty research agenda
Why study
chronic
poverty?
CHRONIC
POVERTY
What are the
characteristics of
chronic poverty?
Who are the
chronically
poor?
What are the causes
of chronic poverty,
and what processes
facilitate entry into, or
impede exit from it?
What methods
are available for
the study of
chronic poverty?
To draw attention to those
likely to have benefited least,
or suffered mo

================================================================================
DOC 4
human, social-cultural, social-political, financial/material and environmental/natural. An
analysis of the ways in which severity and multi-dimensionality are often characteristics
of chronic poverty, and a brief review of the relevance of the World Bank’s Voices of
the Poor studies to an understanding of chronic poverty, conclude this section.
The chronic poor, it is argued, are a heterogeneous group. There are several sets of
people who are particularly susceptible to chronic poverty, and that

================================================================================
DOC 5
means by which study of chronic poverty is presently undertaken, and will continue to
have an important role to play in research. Our understanding of chronic poverty is also
likely to draw upon notions of both absolute and relative poverty, vulnerability, social
exclusion, and capabilities and freedoms, as well as upon subjective assessments by
the poor themselves.
In the third section, the characteristics of chronic poverty are presented. Long duration
is identified as both necessary and suffi

Загружаем два Cross-Encoder:

In [8]:
BASELINE_RERANKER = "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"
ALTERNATIVE_RERANKER = "cross-encoder/ms-marco-MiniLM-L6-v2"

In [11]:
reranker_baseline = CrossEncoder(BASELINE_RERANKER, device="cpu")
reranker_alternative = CrossEncoder(ALTERNATIVE_RERANKER, device="cpu")

config.json:   0%|          | 0.00/891 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/435 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Нам важно видеть именно порядок документов после reranking, поэтому сделаем простую функцию, которая возвращает и документ, и скор:

In [12]:
def rerank_documents(query, documents, reranker, top_k=5):
    pairs = [(query, doc.page_content) for doc in documents]

    scores = reranker.predict(pairs)

    ranked = sorted(zip(documents, scores), key=lambda x: x[1], reverse=True)

    return ranked[:top_k]

Проверка на одном запросе:

In [13]:
baseline_ranked = rerank_documents(
    test_query,
    retrieved_docs,
    reranker_baseline,
    top_k=5,
)

alternative_ranked = rerank_documents(
    test_query,
    retrieved_docs,
    reranker_alternative,
    top_k=5,
)

In [14]:
print("BASELINE RERANKER")

for i, (doc, score) in enumerate(baseline_ranked, start=1):
    print("\n" + "=" * 80)
    print(f"Rank: {i}")
    print(f"Score: {score:.4f}")
    print(doc.page_content[:400])


print("\n\nALTERNATIVE RERANKER")

for i, (doc, score) in enumerate(alternative_ranked, start=1):
    print("\n" + "=" * 80)
    print(f"Rank: {i}")
    print(f"Score: {score:.4f}")
    print(doc.page_content[:400])

BASELINE RERANKER

================================================================================
Rank: 1
Score: 7.4557
by measures of deficits in current consumption and expenditure. It will be important for
CPRC researchers to engage with these issues of vulnerability, both in terms of
differential vulnerabilities to shocks leading to spells of poverty, as well the manner in
which vulnerability interacts with risk aversion to hinder escape from poverty, through,
for example, adverse incorporation (Wood 2000).6
3

================================================================================
Rank: 2
Score: 6.9821
means by which study of chronic poverty is presently undertaken, and will continue to
have an important role to play in research. Our understanding of chronic poverty is also
likely to draw upon notions of both absolute and relative poverty, vulnerability, social
exclusion, and capabilities and freedoms, as well as upon subjective assessments by
the poor themselves.
In the third section, the chara

================================================================================
Rank: 3
Score: 6.3463
human, social-cultural, social-political, financial/material and environmental/natural. An
analysis of the ways in which severity and multi-dimensionality are often characteristics
of chronic poverty, and a brief review of the relevance of the World Bank’s Voices of
the Poor studies to an understanding of chronic poverty, conclude this section.
The chronic poor, it is argued, are a heterogeneous g

================================================================================
Rank: 4
Score: 6.0045
28
Table 5: ‘Assets’ and the chronic poor
Dimension of poverty/well-being Characteristics of the chronically poor Significance for the chronically poor, in terms of
ease/difficulty of realisation or upward mobility
Physical assets: land, livestock, house,
other
• Landless (or livestock-less, in pastoral contexts), near
landless, marginal land; limited access to necessary
inputs (e.g. labour, irrig

================================================================================
Rank: 5
Score: 4.7958
7
Poverty based on adverse
incorporation – the
‘productive poor, e.g.
bonded, indentured labour
Figure 1: Chronic poverty research agenda
Why study
chronic
poverty?
CHRONIC
POVERTY
What are the
characteristics of
chronic poverty?
Who are the
chronically
poor?
What are the causes
of chronic poverty,
and what processes
facilitate entry into, or
impede exit from it?
What methods
are available for
the


ALTERNATIVE RERANKER

================================================================================
Rank: 1
Score: 7.1377
means by which study of chronic poverty is presently undertaken, and will continue to
have an important role to play in research. Our understanding of chronic poverty is also
likely to draw upon notions of both absolute and relative poverty, vulnerability, social
exclusion, and capabilities and freedoms, as well as upon subjective assessments by
the poor themselves.
In the third section, the chara

================================================================================
Rank: 2
Score: 6.7741
by measures of deficits in current consumption and expenditure. It will be important for
CPRC researchers to engage with these issues of vulnerability, both in terms of
differential vulnerabilities to shocks leading to spells of poverty, as well the manner in
which vulnerability interacts with risk aversion to hinder escape from poverty, through,
for example, adverse incorporation (Wood 2000).6
3

================================================================================
Rank: 3
Score: 6.6921
human, social-cultural, social-political, financial/material and environmental/natural. An
analysis of the ways in which severity and multi-dimensionality are often characteristics
of chronic poverty, and a brief review of the relevance of the World Bank’s Voices of
the Poor studies to an understanding of chronic poverty, conclude this section.
The chronic poor, it is argued, are a heterogeneous g

================================================================================
Rank: 4
Score: 5.9999
7
Poverty based on adverse
incorporation – the
‘productive poor, e.g.
bonded, indentured labour
Figure 1: Chronic poverty research agenda
Why study
chronic
poverty?
CHRONIC
POVERTY
What are the
characteristics of
chronic poverty?
Who are the
chronically
poor?
What are the causes
of chronic poverty,
and what processes
facilitate entry into, or
impede exit from it?
What methods
are available for
the

================================================================================
Rank: 5
Score: 5.1985
3
Table of contents
Title page and acknowledgements 1
Abstract 2
Table of contents 3
List of figures and list of tables 4
Abbreviations 4
1 Background 5
2 Frameworks for understanding and measuring poverty 6
2.1 Material poverty, money-metric measurement approaches and multi-
dimensional concepts of poverty
6
2.2 Absolute and relative poverty 8
2.3 Subjective poverty assessments 8
2.4 Capabilities

### Сравнение Cross-Encoder моделей

Для двух reranker-моделей используется одинаковый исходный hybrid retrieval.  
Таким образом, различия в порядке документов и итоговых ответах связаны именно с этапом reranking.

Для сравнения используются три вопроса по разным PDF-документам:

- chronic poverty paper;
- information security audit report;
- PowerPoint 2010 training guide.

In [15]:
test_questions = [
    "What are the main characteristics of chronic poverty?",
    "What were the main findings and recommendations of the information security audit?",
    "What are the main features and tasks explained in the PowerPoint 2010 training guide?",
]

In [16]:
def get_doc_info(doc):
    source = Path(doc.metadata.get("source", "")).name
    page = doc.metadata.get("page", None)

    return source, page

Получаем результаты реранкера:

In [17]:
rerank_results = {}

for question in test_questions:
    print("\n" + "#" * 100)
    print("QUESTION:", question)

    # Один и тот же retrieval для обоих reranker
    retrieved_docs = hybrid_retriever.invoke(question)

    baseline_ranked = rerank_documents(
        question,
        retrieved_docs,
        reranker_baseline,
        top_k=5,
    )

    alternative_ranked = rerank_documents(
        question,
        retrieved_docs,
        reranker_alternative,
        top_k=5,
    )

    rerank_results[question] = {
        "baseline": baseline_ranked,
        "alternative": alternative_ranked,
    }

    print("\nBASELINE RERANKER")

    for rank, (doc, score) in enumerate(baseline_ranked, start=1):
        source, page = get_doc_info(doc)

        print(
            f"{rank}. score={score:.4f} | "
            f"source={source} | page={page}"
        )
        print(doc.page_content[:250].replace("\n", " "))
        print()

    print("\nALTERNATIVE RERANKER")

    for rank, (doc, score) in enumerate(alternative_ranked, start=1):
        source, page = get_doc_info(doc)

        print(
            f"{rank}. score={score:.4f} | "
            f"source={source} | page={page}"
        )
        print(doc.page_content[:250].replace("\n", " "))
        print()

####################################################################################################
QUESTION: What are the main characteristics of chronic poverty?

BASELINE RERANKER
1. score=7.4557 | source=0008-pdf.pdf | page=9
by measures of deficits in current consumption and expenditure. It will be important for CPRC researchers to engage with these issues of vulnerability, both in terms of differential vulnerabilities to shocks leading to spells of poverty, as well the

2. score=6.9821 | source=0008-pdf.pdf | page=1
means by which study of chronic poverty is presently undertaken, and will continue to have an important role to play in research. Our understanding of chronic poverty is also likely to draw upon notions of both absolute and relative poverty, vulnerab

3. score=6.3463 | source=0008-pdf.pdf | page=1
human, social-cultural, social-political, financial/material and environmental/natural. An analysis of the ways in which severity and multi-dimensionality are often characteristics of chronic poverty, and a brief review of the relevance of the World

4. score=6.0045 | source=0008-pdf.pdf | page=27
28 Table 5: ‘Assets’ and the chronic poor Dimension of poverty/well-being Characteristics of the chronically poor Significance for the chronically poor, in terms of ease/difficulty of realisation or upward mobility Physical assets: land, livestock, h

5. score=4.7958 | source=0008-pdf.pdf | page=6
7 Poverty based on adverse incorporation – the ‘productive poor, e.g. bonded, indentured labour Figure 1: Chronic poverty research agenda Why study chronic poverty? CHRONIC POVERTY What are the characteristics of chronic poverty? Who are the chronica


ALTERNATIVE RERANKER
1. score=7.1377 | source=0008-pdf.pdf | page=1
means by which study of chronic poverty is presently undertaken, and will continue to have an important role to play in research. Our understanding of chronic poverty is also likely to draw upon notions of both absolute and relative poverty, vulnerab

2. score=6.7741 | source=0008-pdf.pdf | page=9
by measures of deficits in current consumption and expenditure. It will be important for CPRC researchers to engage with these issues of vulnerability, both in terms of differential vulnerabilities to shocks leading to spells of poverty, as well the

3. score=6.6921 | source=0008-pdf.pdf | page=1
human, social-cultural, social-political, financial/material and environmental/natural. An analysis of the ways in which severity and multi-dimensionality are often characteristics of chronic poverty, and a brief review of the relevance of the World

4. score=5.9999 | source=0008-pdf.pdf | page=6
7 Poverty based on adverse incorporation – the ‘productive poor, e.g. bonded, indentured labour Figure 1: Chronic poverty research agenda Why study chronic poverty? CHRONIC POVERTY What are the characteristics of chronic poverty? Who are the chronica

5. score=5.1985 | source=0008-pdf.pdf | page=2
3 Table of contents Title page and acknowledgements 1 Abstract 2 Table of contents 3 List of figures and list of tables 4 Abbreviations 4 1 Background 5 2 Frameworks for understanding and measuring poverty 6 2.1 Material poverty, money-metric measure


####################################################################################################
QUESTION: What were the main findings and recommendations of the information security audit?

BASELINE RERANKER
1. score=0.8248 | source=0007-pdf.pdf | page=1
Summary and Overall Conclusions  Introduction and objectives  1.1 In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to  assess the extent to which confidential, person

2. score=0.5692 | source=0007-pdf.pdf | page=3
3.3 Overall, there is currently satisfactory management of risk but a number of weaknesses were identified. An acceptable control environment  is in operation but there are a number of improvements that should be made. Our opinion of the controls wit

3. score=0.3541 | source=0007-pdf.pdf | page=1
it was also observed that past improvements in informatio n security had not been maintained, with large numbers of cupboards being left  unsecured and sensitive, personal and confidential information was insufficiently protected. As a result, it was

4. score=-1.7261 | source=0007-pdf.pdf | page=1
number of non council staff who share West Offices makes it more important for each service to recognise the importance to se cure the  information they hold within their area of the building.  1.4 The buildings were visited after most staff had left

5. score=-2.4355 | source=0007-pdf.pdf | page=2
vehicles.    Whilst the Hazel Court site and building security p rovides protection against external breaches of information, reliance should not be  placed solely on the perimeter security and sensitive information must also be protected from intern


ALTERNATIVE RERANKER
1. score=3.3302 | source=0007-pdf.pdf | page=1
Summary and Overall Conclusions  Introduction and objectives  1.1 In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to  assess the extent to which confidential, person

2. score=1.5758 | source=0007-pdf.pdf | page=1
it was also observed that past improvements in informatio n security had not been maintained, with large numbers of cupboards being left  unsecured and sensitive, personal and confidential information was insufficiently protected. As a result, it was

3. score=0.8999 | source=0007-pdf.pdf | page=3
3.3 Overall, there is currently satisfactory management of risk but a number of weaknesses were identified. An acceptable control environment  is in operation but there are a number of improvements that should be made. Our opinion of the controls wit

4. score=-0.8618 | source=0007-pdf.pdf | page=6
Annex 3  Detailed Findings      Information Security  checks Mar17 - consolidated findings.xls

5. score=-1.5029 | source=0007-pdf.pdf | page=4
will be asked to respond with details of what action will be taken to address the  issue and these will be followed up by internal audit.  Audit will provide updates to GRAG on responses received from service areas.  Priority 2  Responsible Officer


####################################################################################################
QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?

BASELINE RERANKER
1. score=-0.6406 | source=0009-pdf.pdf | page=12
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 13  Creating a presentation  CONCLUDING REMARKS          Congratulations!   You have now completed the Creating a presentation booklet.  This booklet was  designed to get yo

2. score=-0.7001 | source=0009-pdf.pdf | page=4
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 5  Creating a presentation  DESIGNING A PRESENTATION                                                    The design and layout of your  presentation will affect whether you g

3. score=-2.2549 | source=0009-pdf.pdf | page=8
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 9  Creating a presentation  TYPING TEXT INTO THE OUTLINE PANE                                                    For Your Reference…  To type text into the Outline pane:  1.

4. score=-2.3793 | source=0009-pdf.pdf | page=6
on My Templates to display the New  Presentation dialog box. Click on a template,  then click on [OK].     PowerPoint 2010 comes complete with a  range of sample templates that you can  use. Each template already contains a  particular design and lay

5. score=-3.1812 | source=0009-pdf.pdf | page=2
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 3  Creating a presentation  PLANNING A PRESENTATION                                                  The first stage in creating a presentation is  the planning phase. At th


ALTERNATIVE RERANKER
1. score=2.0592 | source=0009-pdf.pdf | page=12
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 13  Creating a presentation  CONCLUDING REMARKS          Congratulations!   You have now completed the Creating a presentation booklet.  This booklet was  designed to get yo

2. score=0.2034 | source=0009-pdf.pdf | page=4
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 5  Creating a presentation  DESIGNING A PRESENTATION                                                    The design and layout of your  presentation will affect whether you g

3. score=-1.1926 | source=0009-pdf.pdf | page=3
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 4  Creating a presentation  PRESENTATION METHODS AND HARDWARE                                                    Presentations can be made in a variety of  ways and with a r

4. score=-2.1428 | source=0009-pdf.pdf | page=2
Microsoft PowerPoint 2010 - Level 1  © Learning and Development Service Page 3  Creating a presentation  PLANNING A PRESENTATION                                                  The first stage in creating a presentation is  the planning phase. At th

5. score=-2.5269 | source=0009-pdf.pdf | page=6
on My Templates to display the New  Presentation dialog box. Click on a template,  then click on [OK].     PowerPoint 2010 comes complete with a  range of sample templates that you can  use. Each template already contains a  particular design and lay

Теперь используем top-5 каждого reranker как контекст для одной и той же LLM.

In [18]:
rag_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """Answer the question using only the provided context.
If the context does not contain enough information, say so.
Give a concise and factual answer."""
    ),
    (
        "human",
        """Context:

{context}

Question:
{question}"""
    ),
])

In [19]:
def generate_rag_answer(question, ranked_documents):
    context = "\n\n".join(doc.page_content for doc, score in ranked_documents)

    chain = rag_prompt | _llm | StrOutputParser()

    return chain.invoke({"context": context, "question": question})

In [20]:
answer_results = []

for question in test_questions:
    print("\n" + "#" * 100)
    print("QUESTION:", question)

    baseline_answer = generate_rag_answer(
        question,
        rerank_results[question]["baseline"],
    )

    alternative_answer = generate_rag_answer(
        question,
        rerank_results[question]["alternative"],
    )

    answer_results.append({
        "question": question,
        "baseline_answer": baseline_answer,
        "alternative_answer": alternative_answer,
    })

    print("\nBASELINE ANSWER:\n")
    print(baseline_answer)

    print("\nALTERNATIVE ANSWER:\n")
    print(alternative_answer)

####################################################################################################
QUESTION: What are the main characteristics of chronic poverty?

BASELINE ANSWER:

The main characteristics of chronic poverty are:

* **Extended duration** – long‑term, persistent poverty is the defining (necessary and sufficient) feature; short‑term severe or multi‑dimensional poverty is not chronic.
* **Severity** – chronic poverty is typically severe in its impact.
* **Multi‑dimensionality** – it spans several domains (human, social‑cultural, social‑political, financial/material, environmental/natural) rather than being limited to income alone.
* **Heterogeneity** – the chronically poor form a diverse group with overlapping vulnerabilities (e.g., life‑cycle stage, discrimination, health constraints, asset deprivation).
* **Asset deprivation** – limited or low‑quality physical and financial assets, few accumulation opportunities, and high risk of asset loss, which reinforces the persistence of poverty.

Together, long duration, severity, and multi‑dimensionality (across the listed dimensions) constitute the core characteristics of chronic poverty.

ALTERNATIVE ANSWER:

The main characteristics of chronic poverty are:

* **Extended duration** – poverty must last a “long” time; long duration is both necessary and sufficient for poverty to be considered chronic.
* **Severity and multi‑dimensionality** – chronic poverty is typically severe and involves multiple deprivations (e.g., human, social‑cultural, social‑political, financial/material, environmental/natural).
* **Intergenerational aspects** – it often persists across generations, creating persistent disadvantage.
* **Heterogeneous group** – the chronically poor comprise diverse sub‑groups with overlapping vulnerabilities (e.g., life‑cycle stage, discrimination, adverse incorporation).

These features together define chronic poverty as a long‑term, severe, and multi‑dimensional condition affecting a varied set of people.

####################################################################################################
QUESTION: What were the main findings and recommendations of the information security audit?

BASELINE ANSWER:

The provided context does not contain the detailed findings and specific recommendations from the audit. It only notes general observations such as unsecured cupboards, insufficient protection of sensitive information, the need for new key‑storage arrangements, and the importance of fostering a security‑aware culture, but it does not list the main findings or the concrete recommendations that were made. Therefore, the detailed main findings and recommendations are not available in the given text.

ALTERNATIVE ANSWER:

**Main findings**

- **Overall opinion:** The audit gave a “Reasonable Assurance” opinion on the controls in place, but a number of weaknesses were identified.
- **Key weaknesses:**
  - Large numbers of cupboards were left unsecured, indicating that past improvements in information‑security practices had not been maintained.
  - Sensitive, personal and confidential information was insufficiently protected.
  - The control environment, while acceptable, requires several improvements to fully safeguard data.

**Recommendations / agreed actions**

1. **Implement new key‑storage arrangements** – the audit plan states that further checks in 2017‑18 will follow the rollout of these arrangements, which should improve compliance with the requirement to lock all cupboards.
2. **Strengthen the security culture** – staff and teams need to recognise the importance of securing data within office and team areas and not rely solely on perimeter controls.
3. **Maintain improvements** – ensure that past security enhancements are sustained and that the clear‑desk policy is consistently applied across both West Offices and Hazel Court.
4. **Follow‑up by internal audit** – service areas will be asked to provide details of actions they will take to address the identified issues, and internal audit will monitor progress.
5. **Report updates to GRAG** – the audit team will provide updates on the responses received from service areas.

These points capture the principal findings and the actions agreed upon to address the identified gaps, based on the information provided in the audit summary.

####################################################################################################
QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?

BASELINE ANSWER:

The guide covers the core workflow for building a PowerPoint 2010 presentation:

1. **Planning a Presentation** – Determining purpose, audience, format, time, and delivery method to shape both content and design.

2. **Designing a Presentation** – Choosing an appropriate layout and using design elements sparingly to keep the message clear and avoid distracting the audience.

3. **Creating a Presentation** –
   * Opening PowerPoint and selecting a template (from the built‑in sample templates or downloaded ones).
   * Structuring slides in the **Outline pane** (adding titles and bullet points using the New Slide button and the  →   •  shortcuts).
   * Optionally typing text directly on slides in the Slide window.

4. **Practicing and Reinforcing Skills** – The concluding section encourages hands‑on experimentation with the learned features to solidify competence.

ALTERNATIVE ANSWER:

The PowerPoint 2010 Level 1 guide focuses on the core workflow for building and delivering effective presentations:

**1. Planning a Presentation**
- Define purpose, audience, format, time, and delivery method.
- Use planning to shape both content and design.

**2. Designing a Presentation**
- Keep slides simple and concise (minimal text).
- Choose an appropriate layout and design; use PowerPoint’s features sparingly to reinforce the message.
- Apply good visual‑design principles to aid audience comprehension.

**3. Creating a Presentation**
- Open PowerPoint and use **File → New** to access available templates.
- Browse **Sample Templates** (or download free ones from Microsoft).
- Select a template that matches the presentation’s tone, then type the content.
- The guide walks through opening a new presentation from a template (e.g., “Training” template).

**4. Presentation Methods & Hardware**
- Discusses equipment options (laptop, desktop, etc.) and how the choice affects audience size, portability, interactivity, and ongoing availability.

**5. Concluding Remarks & Next Steps**
- Encourages hands‑on practice to reinforce skills.
- Provides a reference for repeating tasks and continuing skill development.

### Сравнение результатов reranking

| Вопрос | Совпадение top-5 | Основное изменение | Влияние на ответ |
|---|---:|---|---|
| Chronic poverty | 4/5 | Изменился порядок документов, один chunk был заменён | Небольшое улучшение |
| Information security audit | 3/5 | Alternative поднял документы с выводами и follow-up действиями | Существенное улучшение |
| PowerPoint 2010 guide | 4/5 | Alternative добавил общий раздел про presentation methods & hardware | Улучшение полноты ответа |

### Вывод

Выбор Cross-Encoder заметно повлиял на порядок документов после reranking.

Для вопроса о хронической бедности обе модели нашли почти одинаковые релевантные документы, однако альтернативный reranker выше поставил обзорные фрагменты с основными характеристиками хронической бедности. В результате итоговый ответ точнее выделил межпоколенческую передачу бедности как одну из основных характеристик.

Наиболее заметная разница появилась в вопросе об аудите информационной безопасности. Baseline reranker в основном выбрал общие фрагменты отчёта, поэтому LLM не смогла сформировать полноценный список рекомендаций. Alternative reranker поднял выше фрагменты с результатами аудита и последующими действиями, что позволило получить значительно более содержательный ответ.

Для руководства PowerPoint оба reranker нашли релевантные разделы, но alternative добавил более обзорный фрагмент о способах проведения презентаций и оборудовании. Благодаря этому итоговый ответ охватил больше тем руководства.

Таким образом, Cross-Encoder может существенно влиять на качество RAG даже при одинаковом исходном retrieval. В данном эксперименте `cross-encoder/ms-marco-MiniLM-L6-v2` в среднем формировал более полезный top-k и дал более полные итоговые ответы.

## Задание 2. Настройка гиперпараметров гибридного поиска

Сравниваются несколько конфигураций hybrid retrieval с изменением:

- весов semantic search и BM25;
- embedding-модели;
- числа возвращаемых документов `k`.

Для всех вариантов используются одинаковые вопросы, одна LLM и один Cross-Encoder reranker.  
Сравниваются выбранные документы, итоговые ответы, время поиска и время генерации.

Загрузим второй энкодер для сравнения и создадим для него свой vector store:

In [21]:
embeddings_small = HFEmbeddings(
    model_name="intfloat/multilingual-e5-small",
    device="cpu",
)

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/498k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

In [22]:
vectorstore_small = InMemoryVectorStore(embeddings_small)
vectorstore_small.add_documents(chunks)

['ce221a7f-c87c-4473-9384-6bf923f0089a',
 'b004a981-8485-4854-8ea2-5fa1adaabce5',
 '4c3b59bb-5cb9-4b41-987d-eddf9c26058f',
 '19ea3a41-2e6f-4f6f-abb8-650f80a790dd',
 '174c5ef6-d310-43f5-8643-e78a52ad4023',
 'aea1ea06-fa39-46a7-9f62-b0132f82acf2',
 '908cb07d-5d16-424f-b122-504abed3606b',
 'e2ae7c87-1e33-44cf-b2e4-0e62bbcc9db4',
 '7f9ed90a-5bd6-49ab-b370-7faa15442a7b',
 '930abe86-0647-41df-8523-dea43b20e414',
 'bb8b8cfd-2627-43b2-bb26-7f7eb657733c',
 '51e6f53c-417f-4334-a65e-61e808ecd4f9',
 'e874429a-5501-4956-90cc-222c9507f19f',
 '34610492-6613-4f7a-835f-ce4f349e18f1',
 'a9e687f0-e00c-4a42-b172-d14e99196a13',
 'cda132ed-2363-4a6b-bada-5843c9d023f3',
 'c640f846-18c9-4751-8e99-4becdbb08026',
 '0ae7da07-8933-49c2-8e60-e8a78f217700',
 '7fe39c63-9b02-4a34-83e4-fdb5d2adcd17',
 'bb073186-be61-4ef5-b224-dc25ad3878db',
 '4254adea-b10d-437b-87e9-3df6aff1ff45',
 '073c7955-9552-4c01-b26b-de2e4a94157f',
 'ca10ce9d-94a4-4400-9594-137efc62614f',
 '620f41dd-d47c-4b70-83f2-5b98da97a823',
 '8f577bed-9dcc-46e1-bd4d-ef3dff507831',
 '4ea84f7e-f427-4395-9856-e2a8f7cd0d4f',
 '4c0c5264-bebf-4262-85c6-d7d334ceecb6',
 '2c5342a3-045e-4d39-a066-eb7c602f6414',
 'dcc329cd-6ed9-4a45-aa9c-e8007e07e270',
 '98c3f533-2acd-4cd0-992d-29d79664ab53',
 '16a6e2ee-7cb9-4407-8b31-3f0a7aac07b6',
 '0f699dd8-e496-4b5f-b217-1db21480061c',
 'f0f2ec52-e6f9-4344-b31d-92ba75d84ab7',
 'c2b5d77f-1f57-4911-80cb-d6888a38d7e7',
 '61fdbef3-373e-4f58-83d8-638c01074121',
 '01996dc0-8d15-475b-9c23-5d67d7ad4493',
 'e2b6f048-9b13-4d09-946d-eaa7a3413121',
 '8cb4eb1c-ca79-470e-9f5b-a3a368ac57f3',
 'a7735904-d59a-4067-9ef0-e5e92d6b378f',
 '0e290256-411e-4949-959e-afb85493dd13',
 'b013c99e-9b0f-4671-bfb5-2308b0d2479f',
 '53d672fa-dc7f-4d57-9c01-13f5e75d2c9c',
 'bacf6f81-2080-40f2-962e-348943e8a564',
 'd5e10f34-c386-464b-a966-d4a26a2be9e4',
 '9abfd033-de1c-4dbc-84be-d7d4cd5683cb',
 'c3cff0ff-d440-4ce8-a257-2243561d80f3',
 '3338c4d9-4c4b-49eb-92ce-c94eb4d06822',
 '3a6967fa-f7be-4aff-881b-efea4d655db9',
 '78bdf627-efeb-427c-beba-09f5f0401bf8',
 'a21e110a-7296-47b5-b878-b2999efb559b',
 '25f9a963-e5d1-41bf-b465-d282c1f0a1ed',
 '859db9f2-e69b-4268-abd9-1ee7454d2ebd',
 '33a8fd16-b1e4-4b0f-b51e-591d5d60075d',
 '077feefd-a503-4531-a2fd-59ba6af0d980',
 '99035701-37d7-40b1-95b5-f9986a83889d',
 '51980f10-4e22-478f-b8c9-4b5ca626b66c',
 'bc596234-f49e-45ff-85c4-edeeda372308',
 '31db4b21-d8db-4da3-bcf3-583079cc7e78',
 '197bb222-d4a5-407d-b926-0580c655f11a',
 'bd9330e6-b3b9-46a8-b620-674b0d5c6532',
 '67714d56-6e5f-40cc-a3da-13dec84ca623',
 '6a369b9f-fc5d-423e-b4b8-2edc2d7d22d8',
 '2bffcca4-85b9-4362-a600-b91113c6cd4f',
 '7024f557-f58b-46a7-8a8b-47893274e4f0',
 'd6a36d04-538f-434f-ae88-bccedebfa855',
 'ab9080c3-b509-4c27-b42a-a25ea78cc4be',
 '4b9cb604-72e3-4848-bddd-2648d8b80fa1',
 '5d33f49d-6eb2-4faf-923b-a6b8d89fd08c',
 'd3af1ae9-ad28-4b67-85e5-5b660e76147b',
 '6b82f5e2-89c2-481a-8dd1-2b83c4d54d31',
 '0ab1de84-c812-400a-af70-15e2aa2c45f2',
 '9ba8b8fe-f247-4455-b483-cb6138d2733f',
 '14159bc3-0fa9-4ab6-a69d-ed813c9e5dbb',
 '77f30850-8263-4fd7-b2ba-a96c122e061c',
 '7570ec55-849a-4845-af41-1d1600561061',
 '102a42d3-9451-4eb4-8364-579a61bc0cbf',
 'bc57deff-777e-44c6-bb0c-103e85fd9ca8',
 '7c882ae8-7ac6-49dc-b8ae-d420c8544d3a',
 '300adcaa-5554-4154-8ec7-c2d155083d68',
 '2d425159-bec3-44a8-8bb4-3a7f02779107',
 '464319ac-3fdf-438f-a807-3ff40d652196',
 'd3d45acf-88a5-4186-995a-1f8ea04dd7ff',
 'eea145b9-9cde-4fd7-ac10-0395f76ee3de',
 '3c0d313f-b96e-4d6b-9bf9-c355feb190dc',
 '05aa19da-0191-41fc-aea6-6064529364c5',
 '90b70267-c578-4384-80c5-49c896f73b02',
 '6c61842a-76e3-4d5d-93d3-34e48efcc39c',
 '8adb392a-c0e1-4c46-8e24-b2641cc6e7cd',
 '8a9a4180-bc59-4784-989b-54ff13c2ebc8',
 'f5eebb79-ab87-4cda-9da5-8eefd4fba073',
 'd6553ed7-66b1-43af-88c0-65afdad78754',
 '95fdfb0e-61fd-4028-871a-78a9a7381fd2',
 '8785df68-f69a-4e9a-b993-44bc73791fa0',
 'f3699fe5-47e3-4c07-be5a-fff63102859c',
 'b022a07e-0d60-40c0-af39-c55692649808',
 '1b4512f4-ef3c-4fcf-b5b7-57d2faef9c5d',
 '2ba1aa3c-8c8f-4f17-a388-e4626bb10b8f',
 'e6104e76-5299-4d1d-a253-d4b28f739b6f',
 '8bc5c1ec-be5b-46bc-aeca-bd1ce1530ce8',
 '097d2165-11d4-475b-8b25-01df4fa56443',
 '7d7ed84d-98b4-4c48-afae-f92106d8da61',
 '455ea9e9-2819-4966-9350-ec2a79a7aebc',
 '1b5ffe64-e784-4dd8-be48-24f9d03f8790',
 '68834008-453c-4401-8baf-6f8619f43b32',
 '478e89b5-d7ce-4d73-8851-bc9cccba86e6',
 'c4c2fd01-212e-424f-a1dc-9616f73da020',
 '49b7d7be-c1a7-4279-b946-aa5f1563ccae',
 'dd5af7f5-0f3f-42f8-a003-9a78fa630ed2',
 'ae987594-15c9-4085-a7c0-e04e1f29d1ed',
 'ac00e1fe-653c-45ab-b9ed-661c776b916c',
 '63b8518f-2dcc-4f1a-b91b-90d9e738de77',
 'dcfa947f-c87a-4388-a536-a148618d7838',
 '8bb47332-5e4b-4b1a-a54a-df32c34810ee',
 'ba094b18-1b24-49f6-a7bb-63adbffde745',
 '16208e6a-8bab-4f4b-8d83-42e99b164de7',
 '14d815ca-4eea-4f1e-8467-751f8826e6a8',
 'a1f1a7aa-71f2-4184-9ebb-26fb260c6916',
 '90aa87ef-50e2-46d2-af29-3b6650695915',
 '02231d77-0a94-4fd8-80c9-4c8bb2d5eef9',
 '73f1f7be-cf26-400e-a080-974c5463a07d',
 'b4b6e028-3b7d-42ed-a6d3-a1981220cde9',
 '6889cd27-ff1b-4cf0-ac00-f5adcef39287',
 'd7eba606-d9d5-48c2-adcb-f18d2b0a7d39',
 '84b8a8ba-455f-41de-9da4-3cc0dd71da56',
 'e3be6a24-8d1b-46c1-881d-945075a42c78',
 '9ed01a32-ce41-450a-aca4-7f16cc7e7d99',
 '60bb508c-4c0d-4258-a9fc-15447b32561d',
 '9502cb83-5738-4140-8b89-12f92cb0f285',
 'c31c74f7-f38d-49ef-8b80-ef23f67ffb91',
 '3c49a4e3-3242-4319-b574-61499ec8afd4',
 'ec734f93-3216-4489-bd14-bc1a48737678',
 '792f160b-93d1-4e73-bb24-58687d49c022',
 '99ccc9a1-5a5c-47a2-941a-ff148813f903',
 '3fc345b6-ef7c-434b-bf3a-df3a89163f61',
 '30fc03ad-d00a-43fb-87e5-1524758b678e',
 'a7cb500f-8afb-4ff9-ae58-7a1e89217d71',
 'ef35f231-2207-4d77-b171-624a0390ed9a',
 '48ebd3ce-e8e9-4cd5-929b-6ef67f67bfcb',
 'bd1e7953-1a61-4903-9f5f-db6c2d010986',
 'e230a852-9403-42f9-badc-dbbae8f6dca0',
 '6d3beee2-ee0c-4a24-a89d-7ebc93d1d8fb',
 '7c616494-a01f-43dd-83e7-387a3f8f0998',
 '65a57f33-521f-40c6-8458-78b48bcc7325',
 'a35e411a-665b-4f01-9ba9-c7e5abdb01af',
 '9b7239fd-ec6f-4520-ab57-32d069dca2bf',
 'e04c1464-175e-44c1-b718-2c2c9995813c',
 'ccc9f880-f81b-4236-a103-baf61512d632',
 '273daa1e-b10e-4817-92d4-27f3c5f7fed0',
 '662d106c-59a5-457c-9d5c-35927c4ad59b',
 'ca7da2f8-c325-4984-a119-160f769d4b89',
 '4f7e0535-a080-4d96-aad6-383a1812bd48',
 '061ced21-ed78-438d-82c4-0aed51b386e4',
 'fbdbf305-e60e-4f62-8533-e8b263e5c675',
 'c97d7998-1ad8-4749-8394-6c63b67aaf6c',
 '2eab58bd-9477-4e61-bb8c-f2e0f9acb478',
 'e3594a80-7394-4c09-955c-c3bcaeaa9586',
 '8e5c9e48-f5c0-4e0d-ade0-448f844ff3a8',
 '9e577f1d-8cea-45c3-9f84-72e1912cf968',
 '3933c42c-f95d-4d29-b647-a22bf144ab27',
 'bc0cef14-3af2-4573-81f9-eac84b4314f8',
 'b23692c6-1000-4cd5-a8c7-9728f0dcb924',
 'c5f31583-e863-4c36-ab38-495b43f542fc',
 '5d111869-62d8-4957-9533-3b652cff0068',
 'f05cb1f9-32a9-4cea-8e61-77323182c479',
 '0cf0b16b-57c5-40de-8dde-ddc4402d1026',
 '5b5aea2c-dc14-4042-8607-44c7d6d2e61b',
 '704d2142-d314-4984-a63b-448ee60f97d3',
 'd5dcc891-6c41-40be-bbb1-68f79eb8cb5d',
 'b1cd741c-175f-43e0-96d2-7f43b3bff5da',
 '25b5bf10-6009-41e0-b1ba-b75b4fa79c8d',
 'efc2162e-b454-4a33-a50c-96b014aa0d41',
 'cc28d4b9-a902-4fd0-9dc8-e7d96034145a',
 '237f9f82-d949-4d99-9edf-6d08a2648850',
 '9214d8b3-f676-4068-a01d-6df7af0f9d1d',
 '4918f204-33da-41a0-b624-d4d7dde42d52',
 '14ed8131-bcc3-4f0f-abfa-e3c18d57eb0b',
 'e3edb7fb-f0e0-46e6-b81e-1999cb1b38af',
 '07379e52-38bd-48c7-95d5-bcae16257c73',
 '9e26eec1-27c5-41a6-b14b-d158c81720e3',
 'a97d43c5-29f7-49e5-a220-4c0248958233',
 'd054dea7-b9eb-4878-9aff-fbe80b50351a',
 '5e41baa0-80d8-423e-b2fc-3a3b210599a6',
 '43db927b-63f9-4a46-920c-881efd26caad',
 'be201627-057a-4c5e-bb2e-9a97aeee80db',
 'bf69fdb9-dda7-4c71-8ad1-33a1cdef2085',
 '99022137-8e1a-4159-b38b-37fef7c0eba0',
 '271c2339-4b14-491c-8e02-6dff454a5d70',
 '47073474-e674-466d-b40f-0c84c970a875',
 '3ed022c9-db7f-4339-b176-fa7533340555',
 '75d90225-3d99-4381-99d6-b4c19b70ea8e',
 'fb4f3647-185a-4c20-a944-321b841d5add',
 '6c8e20b4-5f7d-492f-aca2-cc9ffe42d58c',
 '08a8324b-be20-4530-96e5-95f527491c33',
 '86ddb8fb-55c8-45bd-9ee8-101f2191c7b8',
 'e1f44134-e748-4a80-b9ba-767b0f3e478c',
 'd0017a1e-aacc-4fc4-a397-0cf4156383be',
 '0abda922-cdea-429c-836b-5d01bc505cac',
 'cb82be36-cf9f-49bd-82b7-24ab069afc81',
 '2e4f2b80-0663-45fc-9a35-cc15912b4592',
 '565f19b0-1ef4-4d1f-9ff8-d42c4b80c4bf',
 'bc940847-ae7c-43c7-9319-6127c68de12e',
 '24dadfdc-0603-41f8-bedc-2082cab61d86',
 'f9a3afb8-c247-4bf0-bfc9-19382292ed25',
 '9333905a-dd56-4b1a-a7ec-fc02e2f5a7dd',
 '7db4d43a-d0f1-4f8e-a058-c53f71a6c02f',
 '6679aece-0823-402f-998c-7a7208d24208',
 '56c26071-1345-445d-b064-8022a1de3e82',
 '5dc568f4-7894-4c96-abcc-9ff3e84330df',
 'c050b0dd-41af-49c5-96a5-c7ce96783f02',
 'ff87a095-408b-4aa9-b8e2-647bd41cebf4',
 '1ea1f9f0-f775-43fc-b722-0d77bb14b826',
 '42239376-efdf-46ab-8420-897b3812fbe6',
 '795e8c60-82d0-43ac-ae2c-1b49c30b86cb',
 '2be84314-8390-4a81-97dd-a213bf0aedb1',
 '27184109-028f-4a47-afbe-04ba14a42643',
 '5a51d213-ebab-4960-8ca2-f73132b98128',
 '7f9f327a-4e83-473b-9b68-21e07a435522',
 '042e29c9-a558-4e79-b19f-7e4620a516d3',
 'c0881bb3-0ceb-43e2-bf15-da082acfd78c',
 '12868a09-d22f-46b1-bc53-2927c0bfb50c',
 'e34a451b-19b5-4eda-b50b-bf4fe87dd8e5',
 '25a3ca0a-5146-4730-ba19-055b0c8b26fd',
 'ddabafb1-bb8e-4f90-b820-2b558bc5031f',
 'ae1deb78-c624-48ce-a0b8-89305b77e44a',
 '31d4c951-c1e7-4dc8-a431-ef49fce4323f',
 '3ed8655d-c048-40d7-a145-66ed908649d3',
 '2d5751ca-c7ce-434d-9f37-e68ac63f74bb',
 '2fce054a-a99c-4137-adac-eb17eddbbf77',
 '5ae15537-4055-476c-8c81-e73210d3d921',
 'bdb5b7cc-6ca6-4a33-b2a1-088abba7662a',
 '01d96a8a-bcb3-421a-90ff-98e09339f77d',
 '5d92344b-d899-4e9f-9de1-97e3104707f5',
 'bc2a1c87-6b15-4594-af5b-6da44c780d9c',
 'abf956d4-08db-451f-b99a-9be2c3e05fd1',
 'e50ee812-340a-43ac-bb20-21c9cbb0a690',
 '5ccde606-7fba-4c6f-8282-a7a4f599622d',
 'd3357325-4043-417b-b50b-83293a04fcad',
 '84276adf-95bc-4174-b9c3-d99d49e91e7d',
 '8c5735c7-9b78-40e5-a0e0-5e3fa170878f',
 '5b6bda7d-0d61-4e03-bebf-edf1a1cd29c9',
 '506c2258-657d-4d83-b790-56bd84f0a2a0',
 '44486628-42cc-41d1-8ff4-38788d0a2a45',
 '18733fc2-3435-4122-adce-80bedf695162',
 '40ade9bf-5e41-4a84-ab60-07bb2cde97a2',
 '52e7366e-df50-42bb-b241-4b306d1cbbc0',
 'f3eeac0d-713a-4e57-9721-df36d0c21521',
 'a0e35a80-932a-42f2-925b-ea6e0cfcbeaf',
 'd26e330f-2683-4ca2-8223-c57eb745f75e',
 'f2b1281a-8437-43f6-82da-494cfe30eaf0',
 '6904189d-b38a-4b8a-aa32-becb6464634e',
 'd0b61912-a40f-4e2e-a7a9-51c6fd7e97e6',
 'f6a6a979-f278-4d22-b08e-0c214d0b05b5',
 '65326da2-9113-4728-a9cb-9b1b8a2e3de2',
 '3f830b5a-763a-4516-8c60-94188dd54656']

Зададим конфигурации, по которым будем проводить сравнение:

In [23]:
configs = {
    "baseline": {
        "vectorstore": vectorstore,
        "weights": [0.5, 0.5],
        "semantic_k": 10,
        "bm25_k": 10,
    },
    "semantic_heavy": {
        "vectorstore": vectorstore,
        "weights": [0.7, 0.3],
        "semantic_k": 10,
        "bm25_k": 10,
    },
    "bm25_heavy": {
        "vectorstore": vectorstore,
        "weights": [0.3, 0.7],
        "semantic_k": 10,
        "bm25_k": 10,
    },
    "small_k": {
        "vectorstore": vectorstore,
        "weights": [0.5, 0.5],
        "semantic_k": 5,
        "bm25_k": 5,
    },
    "small_encoder": {
        "vectorstore": vectorstore_small,
        "weights": [0.5, 0.5],
        "semantic_k": 10,
        "bm25_k": 10,
    },
}

Важно создавать отдельный BM25 retriever для каждой конфигурации, чтобы изменение k в одном эксперименте не влияло на другие:

In [24]:
def build_hybrid_retriever(config):
    semantic = config["vectorstore"].as_retriever(search_kwargs={"k": config["semantic_k"]})

    bm25 = BM25Retriever.from_documents(chunks)
    bm25.k = config["bm25_k"]

    hybrid = EnsembleRetriever(retrievers=[semantic, bm25], weights=config["weights"])

    return hybrid

Проверим извлечение (пока без вызова LLM). Убедимся, что все конфигурации работают и действительно выбирают разные документы.

In [25]:
retrieval_results = {}

for config_name, config in configs.items():
    print("\n" + "#" * 100)
    print("CONFIG:", config_name)

    retriever = build_hybrid_retriever(config)

    retrieval_results[config_name] = {}

    for question in test_questions:
        start = time.perf_counter()

        retrieved_docs = retriever.invoke(question)

        ranked_docs = rerank_documents(
            question,
            retrieved_docs,
            reranker_alternative,
            top_k=5,
        )

        elapsed = time.perf_counter() - start

        retrieval_results[config_name][question] = {
            "documents": ranked_docs,
            "retrieval_time_sec": elapsed,
        }

        print("\nQUESTION:", question)
        print(f"Search + reranking time: {elapsed:.3f} sec")

        for rank, (doc, score) in enumerate(ranked_docs, start=1):
            source, page = get_doc_info(doc)

            print(
                f"{rank}. source={source} | "
                f"page={page} | score={score:.4f}"
            )

####################################################################################################
CONFIG: baseline

QUESTION: What are the main characteristics of chronic poverty?
Search + reranking time: 2.550 sec
1. source=0008-pdf.pdf | page=1 | score=7.1377
2. source=0008-pdf.pdf | page=9 | score=6.7741
3. source=0008-pdf.pdf | page=1 | score=6.6921
4. source=0008-pdf.pdf | page=6 | score=5.9999
5. source=0008-pdf.pdf | page=2 | score=5.1985

QUESTION: What were the main findings and recommendations of the information security audit?
Search + reranking time: 1.335 sec
1. source=0007-pdf.pdf | page=1 | score=3.3302
2. source=0007-pdf.pdf | page=1 | score=1.5758
3. source=0007-pdf.pdf | page=3 | score=0.8999
4. source=0007-pdf.pdf | page=6 | score=-0.8618
5. source=0007-pdf.pdf | page=4 | score=-1.5029

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Search + reranking time: 1.690 sec
1. source=0009-pdf.pdf | page=12 | score=2.0592
2. source=0009-pdf.pdf | page=4 | score=0.2034
3. source=0009-pdf.pdf | page=3 | score=-1.1926
4. source=0009-pdf.pdf | page=2 | score=-2.1428
5. source=0009-pdf.pdf | page=6 | score=-2.5269

####################################################################################################
CONFIG: semantic_heavy

QUESTION: What are the main characteristics of chronic poverty?
Search + reranking time: 1.573 sec
1. source=0008-pdf.pdf | page=1 | score=7.1377
2. source=0008-pdf.pdf | page=9 | score=6.7741
3. source=0008-pdf.pdf | page=1 | score=6.6921
4. source=0008-pdf.pdf | page=6 | score=5.9999
5. source=0008-pdf.pdf | page=2 | score=5.1985

QUESTION: What were the main findings and recommendations of the information security audit?
Search + reranking time: 1.335 sec
1. source=0007-pdf.pdf | page=1 | score=3.3302
2. source=0007-pdf.pdf | page=1 | score=1.5758
3. source=0007-pdf.pdf | page=3 | score=0.8999
4. source=0007-pdf.pdf | page=6 | score=-0.8618
5. source=0007-pdf.pdf | page=4 | score=-1.5029

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Search + reranking time: 1.701 sec
1. source=0009-pdf.pdf | page=12 | score=2.0592
2. source=0009-pdf.pdf | page=4 | score=0.2034
3. source=0009-pdf.pdf | page=3 | score=-1.1926
4. source=0009-pdf.pdf | page=2 | score=-2.1428
5. source=0009-pdf.pdf | page=6 | score=-2.5269

####################################################################################################
CONFIG: bm25_heavy

QUESTION: What are the main characteristics of chronic poverty?
Search + reranking time: 1.560 sec
1. source=0008-pdf.pdf | page=1 | score=7.1377
2. source=0008-pdf.pdf | page=9 | score=6.7741
3. source=0008-pdf.pdf | page=1 | score=6.6921
4. source=0008-pdf.pdf | page=6 | score=5.9999
5. source=0008-pdf.pdf | page=2 | score=5.1985

QUESTION: What were the main findings and recommendations of the information security audit?
Search + reranking time: 1.833 sec
1. source=0007-pdf.pdf | page=1 | score=3.3302
2. source=0007-pdf.pdf | page=1 | score=1.5758
3. source=0007-pdf.pdf | page=3 | score=0.8999
4. source=0007-pdf.pdf | page=6 | score=-0.8618
5. source=0007-pdf.pdf | page=4 | score=-1.5029

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Search + reranking time: 2.526 sec
1. source=0009-pdf.pdf | page=12 | score=2.0592
2. source=0009-pdf.pdf | page=4 | score=0.2034
3. source=0009-pdf.pdf | page=3 | score=-1.1926
4. source=0009-pdf.pdf | page=2 | score=-2.1428
5. source=0009-pdf.pdf | page=6 | score=-2.5269

####################################################################################################
CONFIG: small_k

QUESTION: What are the main characteristics of chronic poverty?
Search + reranking time: 0.863 sec
1. source=0008-pdf.pdf | page=1 | score=7.1377
2. source=0008-pdf.pdf | page=9 | score=6.7741
3. source=0008-pdf.pdf | page=6 | score=5.9999
4. source=0008-pdf.pdf | page=2 | score=5.1985
5. source=0008-pdf.pdf | page=9 | score=4.4214

QUESTION: What were the main findings and recommendations of the information security audit?
Search + reranking time: 0.748 sec
1. source=0007-pdf.pdf | page=1 | score=3.3302
2. source=0007-pdf.pdf | page=1 | score=1.5758
3. source=0007-pdf.pdf | page=3 | score=0.8999
4. source=0007-pdf.pdf | page=6 | score=-0.8618
5. source=0007-pdf.pdf | page=0 | score=-1.6165

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Search + reranking time: 0.865 sec
1. source=0009-pdf.pdf | page=12 | score=2.0592
2. source=0009-pdf.pdf | page=4 | score=0.2034
3. source=0009-pdf.pdf | page=6 | score=-2.5269
4. source=0009-pdf.pdf | page=11 | score=-3.1764
5. source=0009-pdf.pdf | page=1 | score=-3.3751

####################################################################################################
CONFIG: small_encoder

QUESTION: What are the main characteristics of chronic poverty?
Search + reranking time: 1.597 sec
1. source=0008-pdf.pdf | page=1 | score=7.1377
2. source=0008-pdf.pdf | page=9 | score=6.7741
3. source=0008-pdf.pdf | page=1 | score=6.6921
4. source=0008-pdf.pdf | page=6 | score=5.9999
5. source=0008-pdf.pdf | page=2 | score=5.1985

QUESTION: What were the main findings and recommendations of the information security audit?
Search + reranking time: 1.316 sec
1. source=0007-pdf.pdf | page=1 | score=3.3302
2. source=0007-pdf.pdf | page=1 | score=1.5758
3. source=0007-pdf.pdf | page=3 | score=0.8999
4. source=0007-pdf.pdf | page=6 | score=-0.8618
5. source=0007-pdf.pdf | page=4 | score=-1.5029

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Search + reranking time: 1.549 sec
1. source=0009-pdf.pdf | page=12 | score=2.0592
2. source=0009-pdf.pdf | page=4 | score=0.2034
3. source=0009-pdf.pdf | page=3 | score=-1.1926
4. source=0009-pdf.pdf | page=2 | score=-2.1428
5. source=0009-pdf.pdf | page=6 | score=-2.5269

Главный вывод на этом этапе: веса 0.5/0.5, 0.7/0.3, 0.3/0.7 и смена multilingual-e5-base на multilingual-e5-small почти не изменили итоговый top-5 после reranking. А вот уменьшение k до 5 заметно изменило набор кандидатов и одновременно почти вдвое ускорило поиск.

### Генерация ответов для разных конфигураций

Для каждого варианта hybrid retrieval используется одинаковая LLM и одинаковый Cross-Encoder reranker.

Сравниваются:
- итоговый top-5 документов;
- время retrieval + reranking;
- время генерации;
- содержание финального ответа.

Вызовем LLM для всех сохранённых результатов:

In [26]:
generation_results = []

for config_name, questions_data in retrieval_results.items():
    print("\n" + "#" * 100)
    print("CONFIG:", config_name)

    for question in test_questions:
        ranked_docs = questions_data[question]["documents"]
        retrieval_time = questions_data[question]["retrieval_time_sec"]

        start = time.perf_counter()

        answer = generate_rag_answer(question, ranked_docs)

        generation_time = time.perf_counter() - start

        generation_results.append({
            "config": config_name,
            "question": question,
            "retrieval_time_sec": retrieval_time,
            "generation_time_sec": generation_time,
            "total_time_sec": retrieval_time + generation_time,
            "answer": answer,
        })

        print("\nQUESTION:", question)
        print(f"Retrieval + reranking: {retrieval_time:.3f} sec")
        print(f"Generation: {generation_time:.3f} sec")
        print(f"Total: {retrieval_time + generation_time:.3f} sec")

        print("\nANSWER:\n")
        print(answer)

####################################################################################################
CONFIG: baseline

QUESTION: What are the main characteristics of chronic poverty?
Retrieval + reranking: 2.550 sec
Generation: 6.359 sec
Total: 8.909 sec

ANSWER:

**Main characteristics of chronic poverty (as outlined in the context):**

- **Long duration** – Poverty must persist over an extended period; duration is both necessary and sufficient for a condition to be classified as chronic.
- **Multi‑dimensionality** – Chronic poverty is typically not just income‑based but spans several dimensions (e.g., human, social‑cultural, social‑political, financial/material, environmental/natural).
- **Severity** – It is usually severe (often termed “ultra‑poverty”) and the deficits in consumption and expenditure are substantial.
- **Intergenerational transmission** – Poverty can be passed across generations, reinforcing its persistence.
- **Vulnerability & overlapping risks** – Those in chronic poverty face multiple, intersecting vulnerabilities (e.g., to shocks, discrimination, adverse incorporation) that hinder escape.
- **Heterogeneous group** – The chronically poor are not a uniform class; they include various sub‑groups (e.g., different life‑cycle stages, socially discriminated groups, bonded laborers) with distinct deprivation patterns.

These features together define chronic poverty as a persistent, severe, and multi‑dimensional condition affecting a diverse set of vulnerable populations.

QUESTION: What were the main findings and recommendations of the information security audit?
Retrieval + reranking: 1.335 sec
Generation: 7.102 sec
Total: 8.436 sec

ANSWER:

**Main findings (as reported in the audit summary)**

* **Control weaknesses** – The second round of information‑security checks in 2016/17 identified that past improvements had not been maintained. In particular:
  * Large numbers of cupboards were left **unsecured**.
  * Sensitive, personal and confidential information was **insufficiently protected**.

* **Overall assurance** – Despite these weaknesses, the audit opinion was still **“Reasonable Assurance”** for the controls in place at the time of the audit.

* **Risk management** – Management of risk was judged **satisfactory overall**, but a number of control gaps were noted that should be addressed.

* **Cultural issue** – The audit highlighted the need for a **culture that recognises the importance of securing data** within office and team areas, rather than relying solely on perimeter controls.

**Recommendations (derived from the audit conclusions)**

1. **Implement new key‑storage arrangements** – The audit agreed that further checks in 2017‑18 would be carried out **after** these arrangements are put in place, with the aim of improving compliance with the requirement to lock all cupboards.

2. **Ensure cupboards are locked and data is protected** – Immediate action is required to secure existing cupboards and to protect sensitive, personal and confidential information.

3. **Foster a data‑security culture** – Council departments should promote awareness and ownership of data‑security practices across all teams, not just rely on physical perimeter controls.

4. **Maintain improvements and monitor compliance** – Ongoing monitoring (including the planned 2017‑18 checks) should verify that security measures are sustained and that any new controls are effectively implemented.

5. **Follow‑up by internal audit** – Service areas will be asked to provide details of actions they will take to address the identified issues, and internal audit will follow up on those responses.

*Note:* The detailed findings (e.g., specific locations, exact numbers of unsecured cupboards, etc.) are not included in the provided context (Annex 3 is not reproduced), so the above reflects the main points reported in the audit summary.

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Retrieval + reranking: 1.690 sec
Generation: 8.073 sec
Total: 9.763 sec

ANSWER:

The PowerPoint 2010 Level 1 guide focuses on three core areas:

**1. Planning a presentation**
- Determine the purpose, audience, format, time available and delivery method.
- Use these factors to shape both content and design.

**2. Designing a presentation**
- Keep slides simple and easy to comprehend (minimal text, clear layout).
- Use PowerPoint’s design features sparingly to reinforce the message.
- Choose an appropriate template to set the tone.

**3. Creating a presentation**
- Open PowerPoint and use **File → New** to access the **Available Templates and Themes** dialog.
- Select **Sample Templates** to view installed designs.
- Pick a template (e.g., “Training”) and click **Create** to start a new slide deck.
- Type the text into the pre‑formatted layout.

**Additional topics**
- Presentation methods and hardware options (laptop, desktop, etc.) and how they affect delivery.
- Concluding advice to practice and reinforce the learned skills.

####################################################################################################
CONFIG: semantic_heavy

QUESTION: What are the main characteristics of chronic poverty?
Retrieval + reranking: 1.573 sec
Generation: 5.615 sec
Total: 7.187 sec

ANSWER:

**Main characteristics of chronic poverty**

- **Long duration** – Poverty must persist over an extended period; duration is both necessary and sufficient for a condition to be classified as chronic.
- **Multi‑dimensionality** – Chronic poverty is typically not limited to income alone; it encompasses multiple deprivations (e.g., human, social‑cultural, social‑political, financial/material, environmental/natural).
- **Severity** – It is usually severe, often bordering on “ultra‑poverty,” and the three dimensions of duration, severity, and multi‑dimensionality reinforce each other.
- **Intergenerational transmission** – Poverty can be passed across generations, creating persistent disadvantage.
- **Subjective perception** – The poor’s own assessments of their situation contribute to understanding chronic poverty.
- **Heterogeneous group** – The chronically poor are not a uniform class; they include various sub‑groups (e.g., those discriminated against, those in particular life‑cycle stages, those trapped by adverse incorporation) who face overlapping vulnerabilities.

QUESTION: What were the main findings and recommendations of the information security audit?
Retrieval + reranking: 1.335 sec
Generation: 5.712 sec
Total: 7.047 sec

ANSWER:

**Main findings**

- **Overall opinion:** The audit gave a “Reasonable Assurance” rating to the information‑security controls, but a number of material weaknesses were identified.
- **Unsecured storage:** Large numbers of cupboards were left unlocked, and sensitive, personal or confidential information was not adequately protected.
- **Lack of sustained improvements:** Previous security enhancements (e.g., clear‑desk policy) had not been maintained.
- **Control environment:** While an acceptable control framework is in place, several gaps were noted that could be addressed to strengthen security.
- **Cultural issue:** Reliance on perimeter controls alone was insufficient; a stronger culture of data‑security awareness across all teams was needed.

**Key recommendations**

1. **Implement new key‑storage arrangements** to ensure all cupboards are locked and access is properly controlled.
2. **Reinforce the clear‑desk policy** and ensure it is consistently applied across West Offices and Hazel Court.
3. **Develop a data‑security culture** – train staff and promote awareness that securing data is everyone’s responsibility, not just a perimeter issue.
4. **Schedule follow‑up checks** – conduct further information‑security audits in the 2017‑18 financial year after the new storage arrangements are in place.
5. **Monitor and report on actions** – service areas must provide details of corrective actions, which will be tracked by internal audit and reported to GRAG.

These recommendations aim to close the identified gaps, improve compliance with locking requirements, and sustain the security improvements over time.

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Retrieval + reranking: 1.701 sec
Generation: 7.067 sec
Total: 8.767 sec

ANSWER:

The PowerPoint 2010 Level 1 guide focuses on the core workflow for building and delivering a presentation:

1. **Planning a presentation** – determining purpose, audience, format, time available, and delivery method.
2. **Designing a presentation** – choosing layout, keeping text concise, and using PowerPoint’s visual features only to reinforce the message.
3. **Choosing and using templates** – opening the “New Presentation” dialog, browsing sample templates (e.g., the Training template), and applying a design that matches the presentation’s tone.
4. **Creating the presentation** – the step‑by‑step process of opening PowerPoint, selecting a template, and typing content.
5. **Presentation methods and hardware** – overview of equipment options (laptop, desktop, etc.) and how the choice affects delivery.
6. **Concluding remarks** – encouragement to practice the learned skills and reinforce them through hands‑on use.

These sections together cover the main features and tasks explained in the guide.

####################################################################################################
CONFIG: bm25_heavy

QUESTION: What are the main characteristics of chronic poverty?
Retrieval + reranking: 1.560 sec
Generation: 8.869 sec
Total: 10.430 sec

ANSWER:

The main characteristics of chronic poverty identified in the text are:

* **Extended duration** – poverty must last a “long” time; long duration is both necessary and sufficient for poverty to be considered chronic.
* **Severity** – chronic poverty is typically severe (often described as “ultrapoverty”).
* **Multi‑dimensionality** – it usually involves multiple deprivations across economic, social, cultural, political, material, and environmental dimensions.
* **Intergenerational aspects** – poverty persists across life‑cycle stages and can be transmitted across generations.
* **Heterogeneity** – the chronically poor are a diverse group, including people vulnerable because of life‑cycle stage, social discrimination, adverse incorporation (e.g., bonded or indentured labor), and overlapping vulnerabilities.

These features together define chronic poverty as a long‑lasting, severe, and multi‑dimensional condition affecting a heterogeneous set of individuals.

QUESTION: What were the main findings and recommendations of the information security audit?
Retrieval + reranking: 1.833 sec
Generation: 9.606 sec
Total: 11.439 sec

ANSWER:

**Main Findings**

- **Overall opinion:** The audit gave a “Reasonable Assurance” rating to the information‑security controls, indicating that the general control environment is acceptable.
- **Key weaknesses identified:**
  * Large numbers of storage cupboards were left **unsecured**, allowing confidential, personal and sensitive information to be inadequately protected.
  * Past improvements in information‑security had not been maintained, showing a gap between policy and practice.
  * The control environment, while acceptable, still requires a number of improvements (e.g., ensuring all cupboards are locked, strengthening data‑security practices).
- **Cultural issue:** Reliance on perimeter security alone was noted; a stronger culture that recognises the importance of securing data within each team area is needed.

**Recommendations / Agreed Actions**

1. **Implement new key‑storage arrangements** that will enable all cupboards to be locked, thereby improving compliance with the “lock all cupboards” requirement.
2. **Reinforce the clear‑desk policy** and promote a culture of data security so that staff recognise the importance of protecting information within their own work areas, not just at the building perimeter.
3. **Schedule further information‑security checks** for the 2017‑18 financial year, to be carried out after the new key‑storage arrangements are in place.
4. **Document and report on corrective actions** – service areas will be asked to provide details of the actions they will take, and internal audit will follow up and provide updates to GRAG.

These steps are intended to address the identified gaps, improve compliance, and ensure that the council’s information‑security controls continue to provide reasonable assurance.

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Retrieval + reranking: 2.526 sec
Generation: 4.580 sec
Total: 7.106 sec

ANSWER:

The PowerPoint 2010 Level 1 guide covers the following main features and tasks:

1. **Planning a presentation** – determining purpose, audience, format, time, and delivery method.
2. **Designing a presentation** – layout, minimal text, and using design elements that reinforce the message.
3. **Presentation methods and hardware** – choosing equipment (laptop, desktop, projector, etc.) based on audience size, interactivity, and ongoing availability.
4. **Creating a presentation with templates** – opening PowerPoint, using the “New” dialog, selecting from built‑in sample templates (e.g., the “Training” template), and customizing the design.
5. **Practicing and reinforcing skills** – hands‑on exercises and encouraging continued use of the learned features.

These sections together provide the step‑by‑step tasks needed to competently create, design, and deliver PowerPoint presentations.

####################################################################################################
CONFIG: small_k

QUESTION: What are the main characteristics of chronic poverty?
Retrieval + reranking: 0.863 sec
Generation: 5.704 sec
Total: 6.567 sec

ANSWER:

The main characteristics of chronic poverty, as outlined in the context, are:

* **Long duration** – extended, persistent poverty is the defining (necessary and sufficient) feature.
* **Severity** – chronic poverty is typically severe (often classified as “ultrapoverty”).
* **Multi‑dimensionality** – it usually involves multiple deprivations beyond income.
* **Intergenerational transmission** – poverty persists across generations.
* **Heterogeneity** – the chronically poor form a diverse group with varying circumstances and vulnerabilities.

QUESTION: What were the main findings and recommendations of the information security audit?
Retrieval + reranking: 0.748 sec
Generation: 5.733 sec
Total: 6.481 sec

ANSWER:

**Main Findings**

- **Insufficient physical security** – Many cupboards were left unlocked, leaving sensitive, personal and confidential information inadequately protected.
- **Lack of sustained improvements** – Previous information‑security enhancements had not been maintained.
- **Control weaknesses** – While overall risk management was satisfactory and the control environment was acceptable, a number of specific weaknesses were identified.
- **Cultural gap** – Reliance on perimeter controls alone; staff awareness of the need to secure data at the desk and within team areas was insufficient.

**Recommendations**

1. **Implement new key‑storage arrangements** to ensure all cupboards can be locked, thereby improving compliance with the “lock all cupboards” requirement.
2. **Strengthen the security culture** – embed awareness that data must be secured within each team area and not just at the building perimeter.
3. **Address the identified control weaknesses** – make the improvements noted in the audit report (e.g., better desk‑clearance practices, tighter handling of confidential material).
4. **Schedule follow‑up checks** – continue information‑security checks in 2017‑18 to monitor progress and verify that the new storage arrangements and cultural changes are effective.

These actions aim to move the council’s information‑security posture from “reasonable assurance” to a stronger, more consistently maintained level.

QUESTION: What are the main features and tasks explained in the PowerPoint 2010 training guide?
Retrieval + reranking: 0.865 sec
Generation: 4.187 sec
Total: 5.052 sec

ANSWER:

The guide covers the core tasks and features of **Microsoft PowerPoint 2010**:

**1. Creating a Presentation**
- Plan the presentation’s design and content before building slides.
- Use PowerPoint to combine the design and key ideas quickly.

**2. Designing a Presentation**
- Choose from built‑in **sample templates** (accessed via **File → New → Sample Templates**) or download free templates from Microsoft’s website.
- Apply a template’s layout and design, then add text.
- Follow design guidelines: keep text minimal, be concise, and use visual elements sparingly to reinforce the message.

**3. Previewing a Slide Show**
- **From the beginning:** click **From Beginning** (or press the designated shortcut) in the **Start Slide Show** group on the **Slide Show** tab.
- **From the current slide:** click **From Current Slide**.
- Preview in **Reading View** for a full‑screen view while keeping the taskbar accessible.
- Keyboard shortcuts are provided for quick previewing.

These sections explain how to set up, style, and test a PowerPoint presentation using templates, design best practices, and slide‑show preview options.

####################################################################################################
CONFIG: small_encoder

QUESTION: What are the main characteristics of chronic poverty?
Retrieval + reranking: 1.597 sec
Generation: 4.536 sec
Total: 6.132 sec

ANSWER:

The main characteristics of chronic poverty are:

* **Extended duration** – poverty must last a “long” time; long duration is both necessary and sufficient for poverty to be considered chronic.
* **Severity** – chronic poverty is typically severe (often described as “ultrapoverty”).
* **Multi‑dimensionality** – it usually involves multiple deprivations across economic, social, cultural, political, material and environmental dimensions.
* **Intergenerational aspects** – poverty persists across the life cycle and can be transmitted across generations.
* **Heterogeneous group** – the chronically poor comprise diverse sub‑groups with overlapping vulnerabilities (e.g., due to life‑stage, discrimination, adverse incorporation).

These features together define chronic poverty as a long‑lasting, severe, and multi‑dimensional condition affecting a varied set of people.

QUESTION: What were the main findings and recommendations of the information security audit?
Retrieval + reranking: 1.316 sec
Generation: 4.955 sec
Total: 6.272 sec

ANSWER:

**Main Findings**

- **Overall control environment:** The audit concluded that the council’s information‑security controls provided **reasonable assurance** at the time of the review.
- **Key weaknesses identified:**
  - A large number of storage cupboards were left **unsecured**, meaning confidential, personal and sensitive data were not adequately protected.
  - Past improvements to information‑security practices had **not been maintained**.
  - The current **clear‑desk policy** and related procedures were not consistently applied, especially in shared‑office areas (e.g., West Offices) where many non‑council staff work.
- **Risk management:** While overall risk management was judged satisfactory, several control gaps were noted that could expose the council to data‑security incidents.

**Recommendations / Agreed Actions**

1. **Implement new key‑storage arrangements** to ensure that **all cupboards are locked** and that access to sensitive material is properly controlled.
2. **Strengthen the security culture** across all teams – staff should recognise the importance of securing data both on desks and in storage, and should not rely solely on perimeter controls.

In [27]:
generation_df = pd.DataFrame(generation_results)

summary_df = generation_df[
    [
        "config",
        "question",
        "retrieval_time_sec",
        "generation_time_sec",
        "total_time_sec",
    ]
]

summary_df

,config,question,retrieval_time_sec,generation_time_sec,total_time_sec
0,baseline,What are the main characteristics of chronic p...,2.550131,6.358692,8.908822
1,baseline,What were the main findings and recommendation...,1.334650,7.101598,8.436248
2,baseline,What are the main features and tasks explained...,1.690213,8.072563,9.762776
3,semantic_heavy,What are the main characteristics of chronic p...,1.572504,5.614628,7.187132
4,semantic_heavy,What were the main findings and recommendation...,1.334530,5.712463,7.046993
5,semantic_heavy,What are the main features and tasks explained...,1.700773,7.066668,8.767441
6,bm25_heavy,What are the main characteristics of chronic p...,1.560460,8.869087,10.429548
7,bm25_heavy,What were the main findings and recommendation...,1.832924,9.605585,11.438509
8,bm25_heavy,What are the main features and tasks explained...,2.526252,4.580165,7.106417
9,small_k,What are the main characteristics of chronic p...,0.863000,5.703732,6.566731
10,small_k,What were the main findings and recommendation...,0.747831,5.733478,6.481309
11,small_k,What are the main features and tasks explained...,0.864821,4.187454,5.052275
12,small_encoder,What are the main characteristics of chronic p...,1.596644,4.535798,6.132443
13,small_encoder,What were the main findings and recommendation...,1.316234,4.955294,6.271528
14,small_encoder,What are the main features and tasks explained...,1.549044,4.748469,6.297513

In [28]:
# таблица со средними

avg_summary_df = (
    generation_df
    .groupby("config")[
        [
            "retrieval_time_sec",
            "generation_time_sec",
            "total_time_sec",
        ]
    ]
    .mean()
    .reset_index()
)

avg_summary_df

           config  retrieval_time_sec  generation_time_sec  total_time_sec
0        baseline            1.858331             7.177618        9.035948
1      bm25_heavy            1.973212             7.684946        9.658158
2  semantic_heavy            1.535935             6.131253        7.667189
3   small_encoder            1.487307             4.746520        6.233828
4         small_k            0.825217             5.208221        6.033438

### Сравнение конфигураций

| Конфигурация | Среднее retrieval + reranking | Среднее generation | Среднее total | Изменение качества |
|---|---:|---:|---:|---|
| baseline | 1.86 с | 7.18 с | 9.04 с | Базовый уровень |
| semantic_heavy | 1.54 с | 6.13 с | 7.67 с | Существенных изменений нет |
| bm25_heavy | 1.97 с | 7.68 с | 9.66 с | Существенных изменений нет |
| small_encoder | 1.49 с | 4.75 с | 6.23 с | Качество практически сохранилось |
| small_k | 0.83 с | 5.21 с | 6.03 с | Качество в целом сохранилось |

### Вывод

В эксперименте изменение весов semantic search и BM25 с `0.5/0.5` на `0.7/0.3` и `0.3/0.7` почти не повлияло на итоговый набор документов после reranking. Это показывает, что Cross-Encoder на данном наборе данных сглаживает различия между результатами двух retriever-ов.

Замена `multilingual-e5-base` на более лёгкий `multilingual-e5-small` также практически не изменила top-5 документов, но немного уменьшила среднее время выполнения.

Наиболее заметный эффект дало уменьшение `k` с 10 до 5. Retrieval + reranking ускорился примерно в два раза, а итоговые ответы остались содержательно сопоставимыми с baseline. В отдельных случаях контекст немного изменился, но существенной потери качества не произошло.

Таким образом, для данного набора документов оптимальной конфигурацией оказался вариант с `k=5` для semantic retriever и BM25 при весах `0.5/0.5` и использовании `multilingual-e5-base`. Он обеспечивает лучший баланс между скоростью и качеством ответа.

Более лёгкий `multilingual-e5-small` также показал хорошие результаты и может быть предпочтителен при более строгих ограничениях по вычислительным ресурсам.