# Практическая работа 3. Простые RAG-системы

В ноутбуке рассматриваются базовые этапы построения RAG-пайплайна: парсинг документов, разбиение текста на чанки, работа с векторными базами данных и сравнение LLM через API.

В рамках работы:
- реализуется собственный парсинг PDF, DOCX и TXT;
- сравниваются Qdrant и ChromaDB;
- сравниваются GigaChat и две модели OpenRouter;
- проводятся замеры скорости, памяти, стабильности и качества ответов.

## Задание 1. Собственный парсинг документов

Реализуется простой pipeline для загрузки PDF, DOCX и TXT без использования `unstructured`.

После извлечения текст очищается от лишних пробелов, лишних переносов строк и типичных артефактов PDF, а затем разбивается на чанки фиксированного размера с overlap.

In [1]:
!pip install -q pypdf python-docx

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 20.1 MB/s eta 0:00:00

In [2]:
import os
import re
import time

from pypdf import PdfReader
from docx import Document

import pandas as pd

In [10]:
DATA_DIR = "/content/data"
os.makedirs(DATA_DIR, exist_ok=True)

Загрузка PDF, DOCX и TXT:

In [3]:
def load_pdf(path):
    reader = PdfReader(path)

    pages = []

    for page in reader.pages:
        text = page.extract_text() or ""
        pages.append(text)

    return "\n\n".join(pages)


def load_docx(path):
    doc = Document(path)

    paragraphs = [
        paragraph.text
        for paragraph in doc.paragraphs
        if paragraph.text.strip()
    ]

    return "\n".join(paragraphs)


def load_txt(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()

Выполним простую очистку текста, удалив:

- лишние пробелы;
- переносы;
- битые символы;
- разрывы слов вида exam-\nple.

In [4]:
def clean_text(text):
    # Убираем нулевые и replacement-символы
    text = text.replace("\x00", "")
    text = text.replace("\ufffd", "")

    # Склеиваем слова, разорванные переносом:
    # "exam-\nple" -> "example"
    text = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", text)

    # Нормализуем переводы строк
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Убираем лишние пробелы и табы
    text = re.sub(r"[ \t]+", " ", text)

    # Не более двух последовательных переносов строк
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Убираем пробелы по краям строк
    text = "\n".join(line.strip() for line in text.splitlines())

    return text.strip()

Единый load_document(path):

In [5]:
def load_document(path):
    extension = os.path.splitext(path)[1].lower()

    if extension == ".pdf":
        text = load_pdf(path)

    elif extension == ".docx":
        text = load_docx(path)

    elif extension == ".txt":
        text = load_txt(path)

    else:
        raise ValueError(f"Неподдерживаемый формат: {extension}")

    return clean_text(text)

Разбиение на чанки. Возьмём разумные значения из примера в задании:

- chunk_size = 800 символов
- overlap = 150 символов

In [6]:
def split_into_chunks(
    text,
    chunk_size=800,
    overlap=150,
):
    if overlap >= chunk_size:
        raise ValueError("overlap должен быть меньше chunk_size")

    chunks = []

    start = 0

    while start < len(text):
        end = start + chunk_size

        chunk = text[start:end].strip()

        if chunk:
            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

Проверим pipeline на одном PDF:

In [7]:
path = "/content/data/0007-pdf.pdf"

start = time.perf_counter()

text = load_document(path)

parse_time = time.perf_counter() - start

chunks = split_into_chunks(text)

print("Файл:", os.path.basename(path))
print("Время парсинга:", round(parse_time, 3), "сек.")
print("Объём текста:", len(text), "символов")
print("Количество чанков:", len(chunks))

print("\nПервые 1500 символов:\n")
print(text[:1500])

Файл: 0007-pdf.pdf
Время парсинга: 0.148 сек.
Объём текста: 9911 символов
Количество чанков: 16

Первые 1500 символов:

Information Security Checks (March) 2016/17
City of York Council
Internal Audit Report





Service Area: Corporate and Cross-Cutting
Responsible Officer: Assistant Director, Legal and Governance
Service Manager: Information Governance and Feedback Team Manager
Version: Final
Date Issued: 1 June 2017
Reference: 10260/022

Overall Audit Opinion Reasonable Assurance
Actions
P1 P2 P3
0


3 0

Summary and Overall Conclusions
Introduction and objectives
1.1 In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to
assess the extent to which confidential, personal or sensitive data is stored securely and to ensure that data security is being given
sufficient priority within council departments. This was the second of these checks in this audit year (the first being in September 2016).

1.2 The previous information security checks were conducted in September and gave an overall opinion of Reasonable Assurance. However,
it was also observed that past improvements in informatio n security had not been maintained, with large numbers of cupboards being left
unsecured and sensitive, personal and confidential information was insufficiently protected. As a result, it was agreed that this second
round of checks would be completed in the 2016-17 audit year.
Scope of the Audit
1.3 As part of this audit the two main council offices, West Offices and Hazel Court, were visited. This was the ninth of these information
s

In [8]:
print(chunks[0])

Information Security Checks (March) 2016/17
City of York Council
Internal Audit Report





Service Area: Corporate and Cross-Cutting
Responsible Officer: Assistant Director, Legal and Governance
Service Manager: Information Governance and Feedback Team Manager
Version: Final
Date Issued: 1 June 2017
Reference: 10260/022

Overall Audit Opinion Reasonable Assurance
Actions
P1 P2 P3
0


3 0

Summary and Overall Conclusions
Introduction and objectives
1.1 In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to
assess the extent to which confidential, personal or sensitive data is stored securely and to ensure that data security is being given
sufficient priority within council departments. This was the second of t

По результату уже видно несколько важных вещей:

- текст извлекается успешно и быстро: 0.148 с;
- получено 9911 символов и 16 чанков;
- обычный текст читается нормально;
- структура таблицы в начале документа уже частично потеряна: блок P1 P2 P3 / 0 / 3 0 распался на отдельные строки;
- встречается типичный PDF-артефакт вроде informatio n security, то есть разрыв слова без дефиса текущая очистка пока не исправляет.

Прогоним все файлы и соберём метрики:

In [11]:
FILES = [
    "0007-pdf.pdf",
    "0008-pdf.pdf",
    "0009-pdf.pdf",
    "0050-docx.docx",
    "0082-docx.docx",
    "0003-txt.txt",
]

results = []

for filename in FILES:
    path = os.path.join(DATA_DIR, filename)

    start = time.perf_counter()

    text = load_document(path)

    parse_time = time.perf_counter() - start

    chunks = split_into_chunks(text)

    results.append({
        "file": filename,
        "type": os.path.splitext(filename)[1].lower(),
        "parse_time_sec": parse_time,
        "text_chars": len(text),
        "chunks": len(chunks),
    })

metrics_df = pd.DataFrame(results)

metrics_df

             file   type  parse_time_sec  text_chars  chunks
0    0007-pdf.pdf   .pdf        0.153389        9911      16
1    0008-pdf.pdf   .pdf        0.404209      116462     180
2    0009-pdf.pdf   .pdf        0.726235       25524      40
3  0050-docx.docx  .docx        0.147107       73690     114
4  0082-docx.docx  .docx        0.090766       40824      63
5    0003-txt.txt   .txt        0.002015       13623      21

Выведем небольшие фрагменты для визуальной оценки качества:

In [12]:
for filename in FILES:
    path = os.path.join(DATA_DIR, filename)

    text = load_document(path)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)
    print(text[:1000])

================================================================================
0007-pdf.pdf
================================================================================
Information Security Checks (March) 2016/17
City of York Council
Internal Audit Report





Service Area: Corporate and Cross-Cutting
Responsible Officer: Assistant Director, Legal and Governance
Service Manager: Information Governance and Feedback Team Manager
Version: Final
Date Issued: 1 June 2017
Reference: 10260/022

Overall Audit Opinion Reasonable Assurance
Actions
P1 P2 P3
0


3 0

Summary and Overall Conclusions
Introduction and objectives
1.1 In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to
assess the extent to which confidential, personal or sensitive data is stored securely and to ensure that data security is being given
sufficient priority within council departments. This was the second of these checks in this audit year (the first being in September 2016).

1.2 The previous information security checks were conducted in September and gave an overall opinion of Reasonable Assurance. Howev

================================================================================
0008-pdf.pdf
================================================================================
Chronic poverty: meanings and
analytical frameworks
David Hulme, Karen Moore and
Andrew Shepherd, November 2001
Institute of Development Policy and Management
University of Manchester, Crawford House, Oxford
Road Manchester M13 9GH, United Kingdom
International Development Department
School of Public Policy, University of Birmingham
Birmingham B15 2TT United Kingdom
CPRC Working Paper 2
Chronic Poverty Research Centre
ISBN Number: 1-904049-01-X
Acknowledgements
The authors would like to acknowledge Sam Hickey and Rachel Marcus for their indepth and insightful comments. Thanks also to partners of CPRC for their comments
and particularly to participants at the CPRC ‘South Africa Design Workshop’ (held at
the University of the Western Cape in July 2001).

2
Abstract
This paper provides an overview of the meaning of ‘chronic poverty’, and identifies
frameworks for analysing it. In the first section, the major frameworks for
conceptualising, defining, explaining, and measuring poverty in it

================================================================================
0009-pdf.pdf
================================================================================
WPL_U101
T r a i n i n g G u i d e
3 – Creating a presentation
Microsoft PowerPoint 2010
- Level 1




Microsoft PowerPoint 2010 - Level 1
© Learning and Development Service Page 2 Creating a presentation
CREATING A PRESENTATION


























PowerPoint can be so much fun to use that it would be easy to
jump in and start playing around without planning your
presentation first. Unfortunately, if you try this approach, you
could spend much more time fiddling with your presentation
than is necessary.
The first stage in creating a presentation is to consider the
design of the presentation. You then need to consider the
content − what are the key ideas that you want to get across?
Once you have a design and the content sorted out, you can
use PowerPoint to put these two together quickly and easily to
create a presentation with a professional and consistent
appearance.
In this booklet we will show you how to:
 gain an understanding of some factors that affect
the design of a pre

================================================================================
0050-docx.docx
================================================================================
REGULATION (EU) 2015/…
OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL
of …
laying down measures concerning open internet access
and amending Directive 2002/22/EC
on universal service and users’ rights
relating to electronic communications networks and services
and Regulation (EU) No 531/2012
on roaming on public mobile communications networks
within the Union
(Text with EEA relevance)
THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION,
Having regard to the Treaty on the Functioning of the European Union, and in particular Article 114 thereof,
Having regard to the proposal from the European Commission,
After transmission of the draft legislative act to the national parliaments,
Having regard to the opinion of the European Economic and Social Committee,
Having regard to the opinion of the Committee of the Regions,
Acting in accordance with the ordinary legislative procedure,
Whereas:
(1) This Regulation aims to establish common rules to safeguard equal and non-discriminatory tr

================================================================================
0082-docx.docx
================================================================================
COM (2013) 643 final – 13562/13
COM (2013) 627 final – 13555/13
SWD (2013) 331 final – 13555/13 ADD1
SWD (2013) 332 final – 13555/13 ADD2
Communication from the Commission to the European Parliament, the Council, the Economic and Social Committee and the Committee of the Regions on the Telecommunications Single Market
Proposal for a Regulation of the European Parliament and of the Council laying down measures concerning the European single market for electronic communications and to achieve a Connected Continent, and amending Directives 2002/20/EC, 2002/21/EC and 2002/22/EC and Regulations (EC) no 1211/2009 and (EU) No 531/2012
Commission Staff Working Document Impact Assessment Accompanying the document Proposal for a Regulation of the European Parliament and of the Council laying down measures concerning the European single market for electronic communications and to achieve a Connected Continent, and amending Directives 2002/20/EC, 2002/21/EC and 2002/22/EC and Regulations (EC) no 1

================================================================================
0003-txt.txt
================================================================================
Air Quality Education Pack

Who is this pack for?
This education pack has been created for teachers, with lesson ideas and resources for primary pupils through to sixth form students. The pack has been created to be flexible, allowing teachers to copy and paste ideas and activities into your own lesson plans. Alternatively, use each lesson or activity idea independently.
This education pack will help pupils to understand the key issues around air pollution, where it comes from and show how they can use their influence to help effect change for cleaner, safer air.

What is air quality?
The term “air quality” essentially means the state of the air around us. Good air quality refers to clean, clear, unpolluted air. Clean air is required to maintain the delicate balance of life on earth— not just for humans, but wildlife, vegetation, water and soil. Poor air quality is generally considered to be present when pollutants reach high enough concentrations to endanger human health and/or the en

- TXT извлекается наиболее чисто: структура абзацев сохраняется, артефактов почти нет.
- DOCX тоже извлекается хорошо, но мы берём только текст абзацев, поэтому исходное форматирование, таблицы и часть служебной структуры теряются.
- PDF извлекается заметно хуже:
  - у 0007-pdf.pdf распалась табличная структура;
  - у 0008-pdf.pdf текст в целом читаемый, но видны переносы строк и артефакты вроде склеенных/разорванных слов;
  - у 0009-pdf.pdf сложная вёрстка приводит к большому количеству пустых строк и визуально «рваному» тексту.
  
По скорости всё очень быстро: от 0.002 с для TXT до 0.726 с для самого сложного PDF. По объёму текста больше всего дал 0008-pdf.pdf — 116 462 символа.

### Сравнение с Unstructured

Те же документы обрабатываются через Unstructured API.

Для сравнения фиксируются:
- время парсинга;
- объём извлечённого текста;
- количество чанков;
- качество сохранения структуры документа.

In [23]:
!pip install -q unstructured-transform-client

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.1/94.1 kB 2.4 MB/s eta 0:00:00

In [19]:
from google.colab import userdata

UNSTRUCTURED_API_KEY = userdata.get("UNSTRUCTURED_API_KEY")

In [24]:
from unstructured_transform_client import TransformClient

client = TransformClient(
    api_key=UNSTRUCTURED_API_KEY,
    server_url="https://transform.unstructured.io",
)

In [25]:
def load_with_unstructured(path):
    with open(path, "rb") as f:
        result = client.parse.run(input=f)

    return result.markdown

Unstructured не поддерживает txt, падает с ошибкой, поэтому здесь сравнение проведу только для PDF и DOCX.

In [28]:
UNSTRUCTURED_FILES = [
    "0007-pdf.pdf",
    "0008-pdf.pdf",
    "0009-pdf.pdf",
    "0050-docx.docx",
    "0082-docx.docx",
]

In [30]:
unstructured_results = []
unstructured_texts = {}

for filename in UNSTRUCTURED_FILES:
    path = os.path.join(DATA_DIR, filename)

    start = time.perf_counter()

    text = load_with_unstructured(path)

    parse_time = time.perf_counter() - start

    chunks = split_into_chunks(text)

    unstructured_texts[filename] = text

    unstructured_results.append({
        "file": filename,
        "type": os.path.splitext(filename)[1].lower(),
        "parse_time_sec": parse_time,
        "text_chars": len(text),
        "chunks": len(chunks),
    })

In [31]:
unstructured_df = pd.DataFrame(unstructured_results)
unstructured_df

             file   type  parse_time_sec  text_chars  chunks
0    0007-pdf.pdf   .pdf       30.312340       10245      16
1    0008-pdf.pdf   .pdf       84.010422      119235     184
2    0009-pdf.pdf   .pdf       50.364800       25981      40
3  0050-docx.docx  .docx        3.104502       74264     115
4  0082-docx.docx  .docx        1.640905       41056      64

In [32]:
custom_compare_df = metrics_df[
    metrics_df["file"].isin(UNSTRUCTURED_FILES)
]

comparison_df = custom_compare_df.merge(
    unstructured_df,
    on=["file", "type"],
    suffixes=("_custom", "_unstructured"),
)

comparison_df

,file,type,parse_time_sec_custom,text_chars_custom,chunks_custom,parse_time_sec_unstructured,text_chars_unstructured,chunks_unstructured
0,0007-pdf.pdf,.pdf,0.153389,9911,16,30.312340,10245,16
1,0008-pdf.pdf,.pdf,0.404209,116462,180,84.010422,119235,184
2,0009-pdf.pdf,.pdf,0.726235,25524,40,50.364800,25981,40
3,0050-docx.docx,.docx,0.147107,73690,114,3.104502,74264,115
4,0082-docx.docx,.docx,0.090766,40824,63,1.640905,41056,64

In [33]:
for filename in UNSTRUCTURED_FILES:
    text = unstructured_texts[filename]

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)
    print(text[:1000])

================================================================================
0007-pdf.pdf
================================================================================
Veritau
Assurance Services for
the Public Sector

# Information Security Checks (March) 2016/17
City of York Council
Internal Audit Report

Service Area: Corporate and Cross-Cutting
Responsible Officer: Assistant Director, Legal and Governance
Service Manager: Information Governance and Feedback Team Manager
Version: Final
Date Issued: 1 June 2017
Reference: 10260/022

<table><tr><th></th><th>P1</th><th>P2</th><th>P3</th></tr><tr><td>Actions</td><td>0</td><td>3</td><td>0</td></tr><tr><td>Overall Audit Opinion</td><td colspan="3">Reasonable Assurance</td></tr></table>

# Summary and Overall Conclusions

# Introduction and objectives

1.1    In accordance with the agreed audit plan, information security checks were undertaken during 2016/17. The purpose of these checks is to
assess the extent to which confidential, personal or sensitive data is stored securely and to ensure that data security is being given
sufficient priority within council departments. This was the second of these chec

================================================================================
0008-pdf.pdf
================================================================================
# Chronic poverty: meanings and
analytical frameworks

David Hulme, Karen Moore and
Andrew Shepherd, November 2001

Institute of Development Policy and Management
University of Manchester, Crawford House, Oxford
Road Manchester M13 9GH, United Kingdom

International Development Department
School of Public Policy, University of Birmingham
Birmingham B15 2TT United Kingdom

# CPRC Working Paper 2

Chronic Poverty Research Centre
ISBN Number: 1-904049-01-X

# Acknowledgements

The authors would like to acknowledge Sam Hickey and Rachel Marcus for their in-
depth and insightful comments. Thanks also to partners of CPRC for their comments
and particularly to participants at the CPRC ‘South Africa Design Workshop’ (held at
the University of the Western Cape in July 2001).

# Abstract

This paper provides an overview of the meaning of ‘chronic poverty’, and identifies frameworks for analysing it. In the first section, the major frameworks for conceptualising, defining, explaining, and measuri

================================================================================
0009-pdf.pdf
================================================================================
Training Guide

# Microsoft PowerPoint 2010
- Level 1

# 3   Creating a presentation

CORPORATE LEARNING & DEVELOPMENT

## Microsoft PowerPoint 2010 - Level 1

# CREATING A PRESENTATION

InFocus

PowerPoint can be so much fun to use that it would be easy to
jump in and start playing around without planning your
presentation first. Unfortunately, if you try this approach, you
could spend much more time fiddling with your presentation
than is necessary.

The first stage in creating a presentation is to consider the
design of the presentation. You then need to consider the
content – what are the key ideas that you want to get across?

Once you have a design and the content sorted out, you can
use PowerPoint to put these two together quickly and easily to
create a presentation with a professional and consistent
appearance.

In this booklet we will show you how to:

✓  gain an understanding of some factors that affect
the design of a presentation

✓ gain an understanding of presentation met

================================================================================
0050-docx.docx
================================================================================
10788/15 AD/FC/vm 1 DGE 2 EN

10788/15 AD/FC/vm DGE 2 EN

REGULATION (EU) 2015/…
OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL

of …

laying down measures concerning open internet access
and amending Directive 2002/22/EC
on universal service and users’ rights
relating to electronic communications networks and services
and Regulation (EU) No 531/2012
on roaming on public mobile communications networks
within the Union

(Text with EEA relevance)

THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION,

Having regard to the Treaty on the Functioning of the European Union, and in particular Article 114 thereof,

Having regard to the proposal from the European Commission,

After transmission of the draft legislative act to the national parliaments,

Having regard to the opinion of the European Economic and Social Committee,

Having regard to the opinion of the Committee of the Regions,

Acting in accordance with the ordinary legislative procedure,

Whereas:

(1)	This Regulation

================================================================================
0082-docx.docx
================================================================================
COM (2013) 643 final – 13562/13

COM (2013) 627 final – 13555/13

SWD (2013) 331 final – 13555/13 ADD1

SWD (2013) 332 final – 13555/13 ADD2

Communication from the Commission to the European Parliament, the Council, the Economic and Social Committee and the Committee of the Regions on the Telecommunications Single Market

Proposal for a Regulation of the European Parliament and of the Council laying down measures concerning the European single market for electronic communications and to achieve a Connected Continent, and amending Directives 2002/20/EC, 2002/21/EC and 2002/22/EC and Regulations (EC) no 1211/2009 and (EU) No 531/2012

Commission Staff Working Document Impact Assessment Accompanying the document  Proposal for a Regulation of the European Parliament and of the Council laying down measures concerning the European single market for electronic communications and to achieve a Connected Continent, and amending Directives 2002/20/EC, 2002/21/EC and 2002/22/EC and Regulations (E

### Вывод

Собственный парсер успешно обработал PDF, DOCX и TXT и оказался значительно быстрее Unstructured. Для тестовых файлов время обработки составляло примерно 0.09–0.73 с, тогда как Unstructured требовал от 1.6 до 84 с.

Для обычного линейного текста собственный парсер показывает хорошее качество. Особенно хорошо обрабатываются TXT и DOCX. При работе с PDF заметны типичные ограничения: теряется исходное форматирование, таблицы могут превращаться в последовательность строк, а сложная вёрстка приводит к лишним переносам и другим артефактам.

Unstructured лучше сохраняет структуру документа. Например, таблица в `0007-pdf.pdf` была восстановлена в виде HTML-таблицы, а заголовки, списки и отдельные элементы сложной вёрстки в PDF распознавались более явно. При этом объём извлечённого текста у двух подходов оказался близким.

Таким образом:
- собственный парсер быстрее, проще и не требует внешнего API;
- Unstructured лучше работает со сложной структурой, таблицами и форматированием;
- собственный вариант подходит для простых и предсказуемых документов, особенно если важны скорость и отсутствие внешних зависимостей;
- для универсального production-пайплайна с разнородными и сложными документами предпочтительнее использовать специализированный инструмент вроде Unstructured либо дополнительно развивать собственный парсер.

## Задание 2. Сравнение Qdrant и ChromaDB

Проводится сравнение двух векторных баз данных на одинаковых embeddings и одинаковых наборах документов.

Создаются две коллекции:
- `collection_small` — 1000 документов;
- `collection_large` — 7500 документов.

Для обеих БД используются одинаковая размерность векторов и cosine distance. Сравниваются скорость индексации и поиска, потребление RAM, размер хранилища, стабильность retrieval и поведение при последовательной и параллельной нагрузке.

In [34]:
!pip install -q qdrant-client chromadb sentence-transformers psutil

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 406.5/406.5 kB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 66.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 21.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 100.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 70.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.1/140.1 kB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.3/206.3 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.7/95.7 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.7.1 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.45.0 which is incompatible.
google-adk 2.7.1 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.45.0 which is incompatible.

In [35]:
import os
import time
import shutil
import psutil
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient, models
import chromadb

In [36]:
SMALL_SIZE = 1000
LARGE_SIZE = 7500

QDRANT_PATH = "/content/qdrant_storage"
CHROMA_PATH = "/content/chroma_storage"

Возьмём небольшую популярную модель:

In [37]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

VECTOR_SIZE = embedding_model.get_sentence_embedding_dimension()

print("Vector size:", VECTOR_SIZE)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Vector size: 384

/tmp/ipykernel_2030/3131104053.py:3: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  VECTOR_SIZE = embedding_model.get_sentence_embedding_dimension()

Возьмём тексты из предыдущего задания:

In [38]:
all_chunks = []

for filename in FILES:
    path = os.path.join(DATA_DIR, filename)

    text = load_document(path)
    chunks = split_into_chunks(text)

    all_chunks.extend(chunks)

print("Исходных чанков:", len(all_chunks))

Исходных чанков: 434

Потом создадим нужное количество записей простым повторением, но сделаем записи формально уникальными, добавив Document ID.

In [39]:
def make_dataset(chunks, size):
    docs = []

    for i in range(size):
        base_text = chunks[i % len(chunks)]
        docs.append(f"{base_text}\nDocument ID: {i}")

    return docs

In [40]:
docs_small = make_dataset(all_chunks, SMALL_SIZE)
docs_large = make_dataset(all_chunks, LARGE_SIZE)

print("Small:", len(docs_small))
print("Large:", len(docs_large))

Small: 1000
Large: 7500

Считаем эмбеддинги один раз:

In [42]:
start = time.perf_counter()

embeddings_small = embedding_model.encode(
    docs_small,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

embeddings_large = embedding_model.encode(
    docs_large,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

embedding_time = time.perf_counter() - start

print("Embedding time:", round(embedding_time, 2), "sec")
print("Small shape:", embeddings_small.shape)
print("Large shape:", embeddings_large.shape)

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

Batches:   0%|          | 0/118 [00:00<?, ?it/s]

Embedding time: 620.17 sec
Small shape: (1000, 384)
Large shape: (7500, 384)

### Qdrant

Создаются две локальные коллекции Qdrant с cosine distance и одинаковой размерностью векторов. Измеряются время индексации, изменение потребления RAM и размер хранилища на диске.

In [43]:
# вспомогательные функции

def get_ram_mb():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


def get_dir_size_mb(path):
    total = 0

    for root, dirs, files in os.walk(path):
        for file in files:
            filepath = os.path.join(root, file)
            total += os.path.getsize(filepath)

    return total / 1024 / 1024

In [44]:
# очистка старого хранилища на всякий случай

if os.path.exists(QDRANT_PATH):
    shutil.rmtree(QDRANT_PATH)

qdrant = QdrantClient(path=QDRANT_PATH)

Функция создания и заполнения коллекции:

In [45]:
def benchmark_qdrant_indexing(
    collection_name,
    documents,
    embeddings,
):
    qdrant.create_collection(
        collection_name=collection_name,
        vectors_config=models.VectorParams(
            size=VECTOR_SIZE,
            distance=models.Distance.COSINE,
        ),
    )

    ram_before = get_ram_mb()
    start = time.perf_counter()

    qdrant.upsert(
        collection_name=collection_name,
        points=[
            models.PointStruct(
                id=i,
                vector=embeddings[i].tolist(),
                payload={"text": documents[i]},
            )
            for i in range(len(documents))
        ],
    )

    elapsed = time.perf_counter() - start
    ram_after = get_ram_mb()

    return {
        "collection": collection_name,
        "documents": len(documents),
        "index_time_sec": elapsed,
        "ram_before_mb": ram_before,
        "ram_after_mb": ram_after,
        "ram_increase_mb": ram_after - ram_before,
    }

In [46]:
# индексируем small и large

qdrant_results = []

qdrant_results.append(
    benchmark_qdrant_indexing(
        "collection_small",
        docs_small,
        embeddings_small,
    )
)

qdrant_results.append(
    benchmark_qdrant_indexing(
        "collection_large",
        docs_large,
        embeddings_large,
    )
)

qdrant_index_df = pd.DataFrame(qdrant_results)
qdrant_index_df

,collection,documents,index_time_sec,ram_before_mb,ram_after_mb,ram_increase_mb
0,collection_small,1000,11.894831,1036.957031,1048.722656,11.765625
1,collection_large,7500,80.362706,1048.722656,1134.796875,86.074219

In [47]:
qdrant_disk_mb = get_dir_size_mb(QDRANT_PATH)

print("Qdrant storage size:", round(qdrant_disk_mb, 2), "MB")

Qdrant storage size: 37.77 MB

In [48]:
for collection_name in [
    "collection_small",
    "collection_large",
]:
    info = qdrant.get_collection(collection_name)

    print(
        collection_name,
        "points:",
        info.points_count,
    )

collection_small points: 1000
collection_large points: 7500

### Поиск в Qdrant

Для обеих коллекций выполняются 15 одинаковых поисковых запросов.  
Измеряется среднее время retrieval и проверяется стабильность результатов при повторении одинаковых запросов.

Чтобы не придумывать искусственные запросы вручную, возьмём 15 разных исходных чанков, т.к. сейчас мы просто измеряем производительность, а не качество извлечения.

In [49]:
query_indices = np.linspace(
    0,
    len(all_chunks) - 1,
    15,
    dtype=int,
)

query_texts = [all_chunks[i] for i in query_indices]

query_embeddings = embedding_model.encode(query_texts, normalize_embeddings=True)

print("Queries:", len(query_texts))
print("Shape:", query_embeddings.shape)

Queries: 15
Shape: (15, 384)

In [51]:
def qdrant_search(
    collection_name,
    query_vector,
    limit=5,
):
    result = qdrant.query_points(
        collection_name=collection_name,
        query=query_vector.tolist(),
        limit=limit,
    )

    return result.points

Замеряем 15 запросов:

In [52]:
def benchmark_qdrant_search(
    collection_name,
    query_embeddings,
):
    latencies = []
    result_ids = []

    for query_vector in query_embeddings:
        start = time.perf_counter()

        results = qdrant_search(collection_name, query_vector)

        latency = time.perf_counter() - start

        latencies.append(latency)

        result_ids.append([point.id for point in results])

    return {
        "collection": collection_name,
        "queries": len(query_embeddings),
        "avg_retrieval_ms": np.mean(latencies) * 1000,
        "min_retrieval_ms": np.min(latencies) * 1000,
        "max_retrieval_ms": np.max(latencies) * 1000,
        "result_ids": result_ids,
    }

In [53]:
qdrant_search_small = benchmark_qdrant_search(
    "collection_small",
    query_embeddings,
)

qdrant_search_large = benchmark_qdrant_search(
    "collection_large",
    query_embeddings,
)

qdrant_search_df = pd.DataFrame([
    {
        k: v
        for k, v in result.items()
        if k != "result_ids"
    }
    for result in [
        qdrant_search_small,
        qdrant_search_large,
    ]
])

qdrant_search_df

,collection,queries,avg_retrieval_ms,min_retrieval_ms,max_retrieval_ms
0,collection_small,15,8.953689,4.178889,26.156542
1,collection_large,15,38.261839,24.347573,73.273649

Теперь проверка стабильности - повторим все 15 запросов 3 раза.

In [54]:
def check_qdrant_stability(
    collection_name,
    query_embeddings,
    repeats=3,
):
    all_runs = []

    for _ in range(repeats):
        run = []

        for query_vector in query_embeddings:
            results = qdrant_search(collection_name, query_vector)

            run.append([point.id for point in results])

        all_runs.append(run)

    stable_queries = 0

    for i in range(len(query_embeddings)):
        first_result = all_runs[0][i]

        if all(run[i] == first_result for run in all_runs[1:]):
            stable_queries += 1

    return stable_queries / len(query_embeddings)

In [55]:
small_stability = check_qdrant_stability(
    "collection_small",
    query_embeddings,
)

large_stability = check_qdrant_stability(
    "collection_large",
    query_embeddings,
)

print(
    "Small stability:",
    f"{small_stability * 100:.1f}%"
)

print(
    "Large stability:",
    f"{large_stability * 100:.1f}%"
)

Small stability: 100.0%
Large stability: 100.0%

### Стресс-тест Qdrant

Проводится серия из 20 последовательных и 5 параллельных запросов к большой коллекции. Сравнивается средняя задержка и общее время выполнения.

In [56]:
from concurrent.futures import ThreadPoolExecutor

20 последовательных запросов:

In [59]:
def qdrant_sequential_test(
    collection_name,
    query_vectors,
    n_queries=20,
):
    latencies = []

    start_total = time.perf_counter()

    for i in range(n_queries):
        query_vector = query_vectors[i % len(query_vectors)]

        start = time.perf_counter()

        qdrant_search(collection_name, query_vector)

        latencies.append(time.perf_counter() - start)

    total_time = time.perf_counter() - start_total

    return {
        "mode": "sequential",
        "queries": n_queries,
        "avg_latency_ms": np.mean(latencies) * 1000,
        "total_time_sec": total_time,
    }

5 параллельных запросов:

In [60]:
def qdrant_parallel_test(
    collection_name,
    query_vectors,
    n_queries=5,
):
    def run_query(query_vector):
        start = time.perf_counter()

        qdrant_search(collection_name, query_vector)

        return time.perf_counter() - start

    vectors = [query_vectors[i % len(query_vectors)] for i in range(n_queries)]

    start_total = time.perf_counter()

    with ThreadPoolExecutor(max_workers=n_queries) as executor:

        latencies = list(executor.map(run_query, vectors))

    total_time = time.perf_counter() - start_total

    return {
        "mode": "parallel",
        "queries": n_queries,
        "avg_latency_ms": np.mean(latencies) * 1000,
        "total_time_sec": total_time,
    }

In [61]:
qdrant_stress_results = [
    qdrant_sequential_test(
        "collection_large",
        query_embeddings,
        n_queries=20,
    ),
    qdrant_parallel_test(
        "collection_large",
        query_embeddings,
        n_queries=5,
    ),
]

qdrant_stress_df = pd.DataFrame(qdrant_stress_results)
qdrant_stress_df

         mode  queries  avg_latency_ms  total_time_sec
0  sequential       20        7.345621        0.146996
1    parallel        5      100.029637        0.125243

### ChromaDB

Создаются две локальные коллекции ChromaDB с теми же embeddings и cosine distance.  
Измеряются время индексации, потребление RAM, размер хранилища, скорость retrieval, стабильность результатов и поведение при последовательной и параллельной нагрузке.

In [94]:
if os.path.exists(CHROMA_PATH):
    shutil.rmtree(CHROMA_PATH)

chroma = chromadb.PersistentClient(
    path=CHROMA_PATH
)

In [95]:
collection_small_chroma = chroma.create_collection(
    name="collection_small",
    metadata={"hnsw:space": "cosine"},
)

collection_large_chroma = chroma.create_collection(
    name="collection_large",
    metadata={"hnsw:space": "cosine"},
)

Функция индексации:

In [96]:
def benchmark_chroma_indexing(
    collection,
    collection_name,
    documents,
    embeddings,
    batch_size=1000,
):
    ram_before = get_ram_mb()

    start = time.perf_counter()

    for start_idx in range(0, len(documents), batch_size):
        end_idx = min(start_idx + batch_size, len(documents))

        collection.add(
            ids=[
                str(i)
                for i in range(start_idx, end_idx)
            ],
            documents=documents[start_idx:end_idx],
            embeddings=embeddings[start_idx:end_idx].tolist(),
        )

    elapsed = time.perf_counter() - start

    ram_after = get_ram_mb()

    return {
        "collection": collection_name,
        "documents": len(documents),
        "index_time_sec": elapsed,
        "ram_before_mb": ram_before,
        "ram_after_mb": ram_after,
        "ram_increase_mb": ram_after - ram_before,
    }

In [97]:
chroma_results = []

chroma_results.append(
    benchmark_chroma_indexing(
        collection_small_chroma,
        "collection_small",
        docs_small,
        embeddings_small,
    )
)

chroma_results.append(
    benchmark_chroma_indexing(
        collection_large_chroma,
        "collection_large",
        docs_large,
        embeddings_large,
    )
)

chroma_index_df = pd.DataFrame(chroma_results)
chroma_index_df

,collection,documents,index_time_sec,ram_before_mb,ram_after_mb,ram_increase_mb
0,collection_small,1000,0.783318,1358.296875,1363.390625,5.093750
1,collection_large,7500,7.461037,1363.390625,1365.285156,1.894531

In [98]:
chroma_disk_mb = get_dir_size_mb(CHROMA_PATH)

print(
    "Chroma storage size:",
    round(chroma_disk_mb, 2),
    "MB"
)

Chroma storage size: 63.64 MB

In [99]:
print("collection_small points:", collection_small_chroma.count())

print("collection_large points:", collection_large_chroma.count())

collection_small points: 1000
collection_large points: 7500

Уже видно заметную разницу с Qdrant:

- collection_small: 0.78 с против 11.89 с у Qdrant;
- collection_large: 7.46 с против 80.36 с;
- Chroma заняла больше места на диске: 63.64 MB против 37.77 MB у Qdrant.

### Поиск в ChromaDB

Для обеих коллекций выполняются те же 15 поисковых запросов.  
Измеряется среднее время retrieval и проверяется стабильность результатов при повторных запросах.

In [100]:
def chroma_search(
    collection,
    query_vector,
    limit=5,
):
    result = collection.query(query_embeddings=[query_vector.tolist()], n_results=limit)

    return result["ids"][0]

In [101]:
def benchmark_chroma_search(
    collection,
    collection_name,
    query_embeddings,
):
    latencies = []
    result_ids = []

    for query_vector in query_embeddings:
        start = time.perf_counter()

        ids = chroma_search(collection, query_vector)

        latency = time.perf_counter() - start

        latencies.append(latency)
        result_ids.append(ids)

    return {
        "collection": collection_name,
        "queries": len(query_embeddings),
        "avg_retrieval_ms": np.mean(latencies) * 1000,
        "min_retrieval_ms": np.min(latencies) * 1000,
        "max_retrieval_ms": np.max(latencies) * 1000,
        "result_ids": result_ids,
    }

In [102]:
chroma_search_small = benchmark_chroma_search(
    collection_small_chroma,
    "collection_small",
    query_embeddings,
)

chroma_search_large = benchmark_chroma_search(
    collection_large_chroma,
    "collection_large",
    query_embeddings,
)

chroma_search_df = pd.DataFrame([
    {
        k: v
        for k, v in result.items()
        if k != "result_ids"
    }
    for result in [
        chroma_search_small,
        chroma_search_large,
    ]
])

chroma_search_df

,collection,queries,avg_retrieval_ms,min_retrieval_ms,max_retrieval_ms
0,collection_small,15,1.737194,1.158710,4.349009
1,collection_large,15,1.390324,1.244729,1.905949

Проверка стабильности:

In [103]:
def check_chroma_stability(
    collection,
    query_embeddings,
    repeats=3,
):
    all_runs = []

    for _ in range(repeats):
        run = []

        for query_vector in query_embeddings:
            ids = chroma_search(collection, query_vector)

            run.append(ids)

        all_runs.append(run)

    stable_queries = 0

    for i in range(len(query_embeddings)):
        first_result = all_runs[0][i]

        if all(run[i] == first_result for run in all_runs[1:]):
            stable_queries += 1

    return stable_queries / len(query_embeddings)

In [104]:
small_stability_chroma = check_chroma_stability(
    collection_small_chroma,
    query_embeddings,
)

large_stability_chroma = check_chroma_stability(
    collection_large_chroma,
    query_embeddings,
)

print(
    "Small stability:",
    f"{small_stability_chroma * 100:.1f}%"
)

print(
    "Large stability:",
    f"{large_stability_chroma * 100:.1f}%"
)

Small stability: 100.0%
Large stability: 100.0%

### Стресс-тест ChromaDB

Проводится серия из 20 последовательных и 5 параллельных запросов к большой коллекции. Сравниваются средняя задержка и общее время выполнения.

In [105]:
def chroma_sequential_test(
    collection,
    query_vectors,
    n_queries=20,
):
    latencies = []

    start_total = time.perf_counter()

    for i in range(n_queries):
        query_vector = query_vectors[i % len(query_vectors)]

        start = time.perf_counter()

        chroma_search(collection, query_vector)

        latencies.append(time.perf_counter() - start)

    total_time = time.perf_counter() - start_total

    return {
        "mode": "sequential",
        "queries": n_queries,
        "avg_latency_ms": np.mean(latencies) * 1000,
        "total_time_sec": total_time,
    }

In [106]:
def chroma_parallel_test(
    collection,
    query_vectors,
    n_queries=5,
):
    def run_query(query_vector):
        start = time.perf_counter()

        chroma_search(collection, query_vector)

        return time.perf_counter() - start

    vectors = [query_vectors[i % len(query_vectors)] for i in range(n_queries)]

    start_total = time.perf_counter()

    with ThreadPoolExecutor(max_workers=n_queries) as executor:
        latencies = list(executor.map(run_query, vectors))

    total_time = time.perf_counter() - start_total

    return {
        "mode": "parallel",
        "queries": n_queries,
        "avg_latency_ms": np.mean(latencies) * 1000,
        "total_time_sec": total_time,
    }

In [107]:
chroma_stress_results = [
    chroma_sequential_test(
        collection_large_chroma,
        query_embeddings,
        n_queries=20,
    ),
    chroma_parallel_test(
        collection_large_chroma,
        query_embeddings,
        n_queries=5,
    ),
]

chroma_stress_df = pd.DataFrame(chroma_stress_results)

chroma_stress_df

         mode  queries  avg_latency_ms  total_time_sec
0  sequential       20        5.418016        0.108512
1    parallel        5       12.613202        0.019171

### Итоговое сравнение Qdrant и ChromaDB

| Метрика | Qdrant | ChromaDB |
|---|---:|---:|
| Small collection | 1000 | 1000 |
| Large collection | 7500 | 7500 |
| Размер вектора | 384 | 384 |
| Метрика | Cosine | Cosine |
| Индексация small | 11.89 с | 0.78 с |
| Индексация large | 80.36 с | 7.46 с |
| RAM прирост small | 11.77 MB | 5.09 MB |
| RAM прирост large | 86.07 MB | 1.89 MB |
| Размер хранилища | 37.77 MB | 63.64 MB |
| Retrieval small | 8.95 мс | 1.74 мс |
| Retrieval large | 38.26 мс | 1.39 мс |
| Стабильность small | 100% | 100% |
| Стабильность large | 100% | 100% |
| 20 последовательных запросов | 7.35 мс | 5.42 мс |
| 5 параллельных запросов | 100.03 мс | 12.61 мс |

### Вывод

В проведённом эксперименте ChromaDB показала более высокую скорость индексации и поиска. Для коллекции из 7500 документов индексация заняла 7.46 с против 80.36 с у Qdrant, а среднее время retrieval составило 1.39 мс против 38.26 мс. Обе базы показали 100% стабильность результатов.

При стресс-тесте ChromaDB также показала меньшую задержку как для последовательных, так и для параллельных запросов. При этом Qdrant использовал меньше дискового пространства: 37.77 MB против 63.64 MB.

Для небольших локальных проектов ChromaDB выглядит более удобным вариантом: API простой, локальный запуск не требует отдельного сервера, а в данном эксперименте поиск и индексация оказались быстрее.

Qdrant предоставляет более развитые возможности для production-сценариев: отдельный серверный режим, масштабирование и более гибкую работу с payload и фильтрами. Local mode, использованный в эксперименте, не отражает полностью производительность серверного Qdrant.

Поэтому результаты этого теста показывают преимущество ChromaDB именно для небольшого локального сценария. Для более крупных production-систем Qdrant потенциально лучше масштабируется, однако это требует отдельного тестирования в серверной конфигурации.

## Задание 3. Сравнение GigaChat и OpenRouter

Сравниваются GigaChat и две модели OpenRouter на одинаковых задачах.

Для всех моделей используется единый интерфейс вызова. Измеряются время ответа, длина ответа и количество токенов. Дополнительно проверяются длинный контекст, стабильность API и поведение при серии последовательных запросов.

In [108]:
!pip install -q openai gigachat

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 3.7 MB/s eta 0:00:00

In [109]:
from google.colab import userdata

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")
GIGACHAT_CREDENTIALS = userdata.get("GIGACHAT_CREDENTIALS")

In [112]:
from openai import OpenAI

openrouter_client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

In [131]:
OPENROUTER_SMALL = "cohere/north-mini-code:free"
OPENROUTER_LARGE = "nvidia/nemotron-3-super-120b-a12b:free"

In [114]:
from gigachat import GigaChat

gigachat_client = GigaChat(
    credentials=GIGACHAT_CREDENTIALS,
    scope="GIGACHAT_API_PERS",
    base_url="https://api.giga.chat/v1",
    verify_ssl_certs=False,
)

In [115]:
GIGACHAT_MODEL = "GigaChat-2-Max"

Напишем функции для вызова моделей с ответами в едином формате:

In [132]:
def call_openrouter(model, prompt, max_tokens=500):
    start = time.perf_counter()

    response = openrouter_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0,
        max_tokens=max_tokens,
    )

    elapsed = time.perf_counter() - start

    text = response.choices[0].message.content

    if not text:
        text = "[Финальный ответ отсутствует]"

    return {
        "text": text,
        "time_sec": elapsed,
        "prompt_tokens": response.usage.prompt_tokens,
        "completion_tokens": response.usage.completion_tokens,
        "total_tokens": response.usage.total_tokens,
    }

In [117]:
def call_gigachat(prompt, max_tokens=500):
    start = time.perf_counter()

    response = gigachat_client.chat(
        {
            "model": GIGACHAT_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            "temperature": 0,
            "max_tokens": max_tokens,
        }
    )

    elapsed = time.perf_counter() - start

    text = response.choices[0].message.content

    usage = response.usage

    return {
        "text": text,
        "time_sec": elapsed,
        "prompt_tokens": usage.prompt_tokens,
        "completion_tokens": usage.completion_tokens,
        "total_tokens": usage.total_tokens,
    }

И реализуем абстракцию переключения моделей (единый интерфейс вызова):

In [133]:
def call_model(model_name, prompt, max_tokens=500):

    if model_name == "gigachat":
        return call_gigachat(prompt, max_tokens=max_tokens)

    elif model_name == "openrouter_small":
        return call_openrouter(OPENROUTER_SMALL, prompt, max_tokens=max_tokens)

    elif model_name == "openrouter_large":
        return call_openrouter(OPENROUTER_LARGE, prompt, max_tokens=max_tokens)

    else:
        raise ValueError(f"Unknown model: {model_name}")

Проверка подключения на примере одного запроса:

In [135]:
test_prompt = "Ответь одним предложением: что такое RAG?"

for model_name in [
    "gigachat",
    "openrouter_small",
    "openrouter_large",
]:
    print("\n" + "=" * 80)
    print(model_name)

    result = call_model(
        model_name,
        test_prompt,
        max_tokens=500,
    )

    print("Time:", round(result["time_sec"], 2), "sec")
    print("Prompt tokens:", result["prompt_tokens"])
    print("Completion tokens:", result["completion_tokens"])
    print("Total tokens:", result["total_tokens"])
    print("Answer:", result["text"])

================================================================================
gigachat
Time: 1.45 sec
Prompt tokens: 26
Completion tokens: 40
Total tokens: 66
Answer: RAG (Retrieval-Augmented Generation) — это технология, объединяющая методы извлечения информации из внешних источников с генерацией текста моделями машинного обучения для повышения точности и надежности ответов.

================================================================================
openrouter_small
Time: 0.85 sec
Prompt tokens: 11
Completion tokens: 137
Total tokens: 148
Answer: RAG (Retrieval-Augmented Generation) — это гибридный подход к ИИ, который извлекает релевантные внешние знания и использует их для улучшения точности и связности генерируемых ответов.

================================================================================
openrouter_large
Time: 3.59 sec
Prompt tokens: 28
Completion tokens: 140
Total tokens: 168
Answer: RAG (Retrieval‑Augmented Generation) — это подход, при котором генеративная модель дополняет свои ответы информацией, извлечённой из внешних источников, чтобы повысить их точность и релевантность.

### Основные тесты моделей

Три модели тестируются на одинаковых задачах:

- логическая задача;
- генерация кода;
- аналитический ответ;
- RAG-вопрос по документу.

Для каждого ответа измеряются время генерации, длина ответа и количество токенов.

In [142]:
logic_prompt = """
У Маши, Олега и Иры разные профессии: программист, учитель и врач.

Известно:
- Маша не врач.
- Олег не программист.
- Ира не учитель.
- Учитель — не Маша.

Определи профессию каждого человека.
Кратко объясни ход рассуждений.
"""

code_prompt = """
Напиши функцию Python second_largest_unique(numbers),
которая возвращает второе по величине уникальное число в списке.

Требования:
- дубликаты не должны влиять на результат;
- если уникальных чисел меньше двух, вернуть None;
- приведи код и короткое объяснение.
"""

analytic_prompt = """
Объясни, зачем в машинном обучении данные обычно разделяют
на train, validation и test.

Ответ должен содержать:
1. назначение каждой выборки;
2. почему нельзя постоянно подбирать параметры по test;
3. короткий практический пример.

Ответ дай на русском языке.
"""

Для RAG возьмём документ из первого задания. Сформируем контекст из начала документа:

In [136]:
rag_path = os.path.join(DATA_DIR, "0008-pdf.pdf")
rag_text = load_document(rag_path)
rag_context = rag_text[:6000]

In [139]:
rag_prompt = f"""
Ответь на вопрос, используя только приведённый контекст.
Если ответа в контексте нет, прямо скажи об этом.

Контекст:
{rag_context}

Вопрос:
Как в документе определяется хроническая бедность и какие
характеристики хронической бедности выделяют авторы?

Ответ дай кратко и по существу.
"""

In [143]:
test_prompts = {
    "logic": logic_prompt,
    "code": code_prompt,
    "analytic": analytic_prompt,
    "rag": rag_prompt,
}

MODELS = [
    "gigachat",
    "openrouter_small",
    "openrouter_large",
]

Функция для запуска всех тестов:

In [144]:
benchmark_results = []
model_answers = {}

for task_name, prompt in test_prompts.items():

    model_answers[task_name] = {}

    for model_name in MODELS:

        print("\n" + "=" * 80)
        print(task_name, "|", model_name)

        try:
            result = call_model(model_name, prompt, max_tokens=1000)

            answer = result["text"]

            benchmark_results.append({
                "task": task_name,
                "model": model_name,
                "time_sec": result["time_sec"],
                "answer_chars": len(answer),
                "prompt_tokens": result["prompt_tokens"],
                "completion_tokens": result["completion_tokens"],
                "total_tokens": result["total_tokens"],
            })

            model_answers[task_name][model_name] = answer

            print(
                "Time:",
                round(result["time_sec"], 2),
                "sec"
            )
            print(
                "Tokens:",
                result["total_tokens"]
            )
            print(
                "Length:",
                len(answer),
                "chars"
            )

            print("\nAnswer:\n")
            print(answer)

        except Exception as e:
            print("ERROR:", repr(e))

================================================================================
logic | gigachat
Time: 5.91 sec
Tokens: 190
Length: 379 chars

Answer:

### Ход рассуждений:

Из условий известно следующее:

1. **Учитель** — не Маша и не Ира → значит учителем является Олег.
2. **Маша** не врач и не учитель → следовательно, профессия Маши — программист.
3. Осталась одна профессия (**врач**) и одно имя (**Ира**) → получается, Ира работает врачом.

---

### Ответ:

- **Маша** — программист
- **Олег** — учитель
- **Ира** — врач

================================================================================
logic | openrouter_small
Time: 4.3 sec
Tokens: 707
Length: 1046 chars

Answer:

**Решение**

| Человек | Профессия |
|--------|------------|
| Маша   | программист |
| Олег   | учитель   |
| Ира    | врач       |

**Как мы пришли к этому выводу**

1. **Маша ≠ врач** → Маша может быть либо *программистом*, либо *учителем*.
2. **Олег ≠ программист** → Олег может быть либо *учителем*, либо *врачом*.
3. **Ира ≠ учитель** → Ира может быть либо *программистом*, либо *врачом*.
4. **Учитель ≠ Маша** → Учителем может быть либо Олег, либо Ира.

Теперь рассмотрим, кто может быть учителем.

*Если учителем будет Олег*:
- Олег = учитель.
- Остались профессии *программист* и *врач* для Маши и Иры.
- Маша не может быть врачом (пункт 1), поэтому Маша = программист.
- Тогда Ира = врач.

Все условия выполняются.

*Если учителем будет Ира*:
- Ира = учитель, но пункт 3 гласит, что Ира ≠ учитель → противоречие.
Таким образом, этот случай невозможен.

Следовательно, единственная согласованная расстановка:

- **Маша** → программист
- **Олег** → учитель
- **Ира** → врач

Все четыре условия выполняются, поэтому это единственный ответ.

================================================================================
logic | openrouter_large
Time: 11.33 sec
Tokens: 494
Length: 545 chars

Answer:

**Решение**

1. Учитель ≠ Маша (дано) и учитель ≠ Ира (Ира не учитель).
   → Остаётся только Олег → **Олег — учитель**.

2. Оставшиеся профессии: программист и врач для Маши и Иры.
   - Маша не врач → Маша — программист.
   - Тогда Ира получает оставшуюся профессию → **Ира — врач**.

**Проверка условий**

- Маша не врач – верно (она программист).
- Олег не программист – верно (он учитель).
- Ира не учитель – верно (она врач).
- Учитель не Маша – верно (учитель Олег).

**Ответ:**
Маша — программист, Олег — учитель, Ира — врач.

================================================================================
code | gigachat
Time: 8.61 sec
Tokens: 405
Length: 1332 chars

Answer:

Вот реализация функции `second_largest_unique()` на Python:

```python
def second_largest_unique(numbers):
    # Преобразуем список в множество, чтобы удалить дубликаты
    unique_numbers = set(numbers)

    # Проверяем, достаточно ли уникальных чисел
    if len(unique_numbers) < 2:
        return None

    # Сортируем уникальные числа по убыванию и берем второй элемент
    sorted_unique_numbers = sorted(unique_numbers, reverse=True)
    return sorted_unique_numbers[1]
```

### Объяснение:

1. **Удаление дублей:**
   Используем встроенную структуру данных `set()`, которая автоматически удаляет повторяющиеся элементы.

2. **Проверка количества уникальных чисел:**
   Если уникальных чисел менее двух, функция возвращает `None`.

3. **Поиск второго наибольшего уникального элемента:**
   Сортируем оставшиеся уникальные значения по убыванию и выбираем второй элемент списка.

### Пример использования:

```python
print(second_largest_unique([9, 8, 8, 7, 7]))      # Выведет: 8
print(second_largest_unique([1, 1, 1]))            # Выведет: None
print(second_largest_unique([5, 5, 5, 5, 4]))       # Выведет: 4
print(second_largest_unique([-10, -20, -10, -30]))  # Выведет: -20
```

Таким образом, функция корректно обрабатывает списки с дубликатами и возвращает именно второе наибольшее уникальное значение.

================================================================================
code | openrouter_small
Time: 5.25 sec
Tokens: 704
Length: 1324 chars

Answer:

**Функция**

```python
def second_largest_unique(numbers):
    """
    Возвращает второе по величине уникальное число из списка.

    Дубликаты игнорируются — для определения результата используются только
    уникальные значения. Если в списке меньше двух различных чисел, функция
    возвращает None.

    Параметры:
    numbers (list): Список чисел (int, float и т.д.)

    Возвращает:
    int/float/None: Второе по величине уникальное число или None.
    """
    # Получаем множество уникальных чисел
    unique = set(numbers)

    # Если меньше двух уникальных значений, возвращаем None
    if len(unique) < 2:
        return None

    # Сортируем уникальные значения в порядке убывания и берем второй элемент
    return sorted(unique, reverse=True)[1]
```

**Объяснение**

1. **Уникальные значения** – Преобразуем входной список в `set`, чтобы удалить дубликаты.
2. **Проверка количества** – Если в наборе меньше двух элементов, невозможно определить второе по величине число, поэтому возвращаем `None`.
3. **Поиск второго по величине** – Сортируем набор в порядке убывания (`reverse=True`) и выбираем элемент с индексом `1` (второй по величине).

Функция работает с любыми числовыми типами (int, float) и корректно обрабатывает такие случаи, как пустые списки, одинаковые элементы или только одно уникальное значение.

================================================================================
code | openrouter_large
Time: 3.22 sec
Tokens: 726
Length: 1726 chars

Answer:

**Код**

```python
def second_largest_unique(numbers):
    """
    Возвращает второе по величине уникальное число в списке `numbers`.
    Если уникальных чисел меньше двух – возвращает None.

    Параметры
    ----------
    numbers : iterable of int/float
        Исходная последовательность, может содержать дубликаты.

    Возвращаемое значение
    ---------------------
    int/float or None
        Второе наибольшее уникальное значение или None.
    """
    # 1. Убираем дубликаты – оставляем только уникальные элементы
    uniq = set(numbers)

    # 2. Если уникальных элементов меньше двух – второго максимума нет
    if len(uniq) < 2:
        return None

    # 3. Находим два наибольших значения.
    #    Самый простой способ – отсортировать уникальные числа по убыванию
    #    и взять элемент с индексом 1.
    #    Сложность O(k log k), где k = количество уникальных чисел (k ≤ n).
    second_largest = sorted(uniq, reverse=True)[1]
    return second_largest
```

**Краткое объяснение**

1. `set(numbers)` удаляет все дубликаты, оставляя только уникальные значения.
2. Если после этого в множестве меньше двух элементов, функции невозможно вернуть второе по величине число → возвращаем `None`.
3. Иначе сортируем уникальные числа в порядке убывания (`sorted(..., reverse=True)`) и берём элемент с индексом 1 – это второй наибольший.

Функция работает за O(n + k log k) времени (где *n* – длина входного списка, *k* – число уникальных элементов) и использует O(k) дополнительной памяти для множества. Если требуется строго линейное время, можно заменить сортировку на проход, поддерживающий два наибольших уникальных значения, но для большинства задач представленное решение достаточно просто и эффективно.

================================================================================
analytic | gigachat
Time: 11.92 sec
Tokens: 520
Length: 2131 chars

Answer:

Разделение данных на три части — **train**, **validation** и **test** — является стандартной практикой в машинном обучении. Это позволяет корректно оценивать качество модели и избегать переобучения.

## 1. Назначение каждой выборки:

- **Train (Обучающая выборка)**
Используется непосредственно для тренировки модели. Именно здесь алгоритм учится находить зависимости и закономерности в данных.

- **Validation (Проверочная выборка)**
Применяется для настройки гиперпараметров алгоритма и выбора наилучшей конфигурации модели. Например, подбор количества слоев сети, регуляризации, скорости обучения и др. Эта выборка помогает избежать переобучения на тренировочных данных.

- **Test (Тестовая выборка)**
Служит исключительно для финальной оценки качества уже готовой модели. Она показывает, насколько хорошо модель обобщила знания и способна ли эффективно предсказывать значения на новых, ранее невидимых ей данных.

---

## 2. Почему нельзя постоянно подбирать параметры по тестовым данным?

Постоянная настройка параметров по тестовой выборке приведет к тому, что модель начнет адаптироваться именно к этой выборке, теряя способность правильно обобщать результаты на реальные данные. Иными словами, произойдет переобучение на тестовую выборку, и итоговая оценка станет некорректной и завышенной относительно реальной производительности модели.

---

## 3. Короткий практический пример:

Допустим, вы решаете задачу классификации фотографий автомобилей по маркам («Lada», «Toyota», «BMW»). У вас есть большой датасет фотографий автомобилей.

Вы делите данные следующим образом:

- Train (80%): обучение модели на фотографиях автомобилей.
- Validation (10%): проверка эффективности выбранных гиперпараметров (например, числа фильтров свёрточной сети).
- Test (10%): финальная оценка точности модели на неизвестных ей фотографиях.

После завершения подбора параметров и проверки на валидирующей выборке вы оцениваете точность модели на тестовой выборке всего лишь один раз. Повторная оптимизация по тестовому набору недопустима, иначе результат перестанет отражать реальную производительность модели вне вашего набора данных.

================================================================================
analytic | openrouter_small
Time: 10.39 sec
Tokens: 1064
Length: 3195 chars

Answer:

**Почему данные в машинном обучении обычно разделяются на три части?**

| Часть | Что мы с ней делаем | Зачем это нужно |
|-------|----------------------|----------------|
| **Train (обучающая выборка)** | Обучаем модель – она видит примеры и корректирует свои внутренние параметры (веса). | Модель должна научиться распознавать закономерности, которые затем можно применить к новой, невиданной информации. |
| **Validation (валидационная выборка)** | Используется во время разработки: подбор гиперпараметров (сила регуляризации, глубина дерева, количество скрытых нейронов и т.д.), ранняя остановка, выбор архитектуры и т.д. | Она дает непредвзятую оценку качества модели на данных, которые **еще не** использовались для обучения, что позволяет принимать решения о дообучении, остановке и выборе модели. |
| **Test (тестовая выборка)** | Используется **один раз** в конце – для окончательной, непредвзятой оценки общей способности модели на независимых данных. | Она показывает, как модель будет вести себя в реальных условиях, и защищает от случайного «перепадаивания» данных, которые могли бы завысить оценку. |

---

### 1. Назначение каждой выборки

* **Обучающая выборка** – это «пособие», с которым модель работает. Она видит множество примеров и извлекает из них правила.
* **Валидационная выборка** – это «контрольная работа», которую мы решаем во время разработки. Она помогает нам решить, какие гиперпараметры или архитектура дают наилучшие результаты, и предотвращает переобучивание на обучающей выборке.
* **Тестовая выборка** – это «итоговый экзамен», который мы сдаем после того, как все решения приняты. Она никогда не используется в процессе разработки, чтобы оценка оставалась честной.

---

### 2. Почему нельзя постоянно подбирать параметры по тестовой выборке

* **Перепадаивание данных** – если тестовая выборка влияет на выбор гиперпараметров, модель «запоминает» ее статистику. Тогда тестовая оценка больше не является независимой – она будет завышенной.
* **Оптимизация под конкретную тестовую выборку** – постоянное использование одних и тех же тестовых данных для улучшения модели приводит к тому, что модель оптимизируется под их особенности, а не под распределение данных в реальном мире.
* **Недостаток данных** – тестовая выборка обычно является ограниченным ресурсом; ее использование в процессе разработки уменьшает объем данных, доступных для обучения, что может снизить общую эффективность модели.

Короче говоря, тестовая выборка – это **последнее** невидимое распределение, которое мы сохраняем, чтобы получить честную оценку. Использование ее для настройки параметров уничтожает эту защиту.

---

### 3. Короткий практический пример

Предположим, мы хотим построить **классификатор спама** на наборе данных из 10 000 писем.

| Раздел | Количество писем | Назначение |
|------|----------------|-----------|
| Обучающая выборка | 6 000 | Обучение модели Naïve Bayes (или логистической регрессии). |
| Валидационная выборка | 2 000 | Попробовать различные значения параметра сглаживания `α` (например, 0.5, 1, 2). Для каждого значения мы обучаем модель на обучающей выборке, оцениваем ее на валидационной выборке и выбираем `α`, которое дает наилучшую точность

================================================================================
analytic | openrouter_large
Time: 9.3 sec
Tokens: 926
Length: 2671 chars

Answer:

**1. Назначение каждой выборки**

| Выборка | Что делаем | Зачем |
|--------|------------|-------|
| **Train (обучающая)** | Обучаем модель: подбираем веса, коэффициенты, гиперпараметры (если они не требуют отдельной валидации). | На этом наборе модель учится находить закономерности в данных. |
| **Validation (валидационная)** | Оцениваем промежуточные результаты, подбираем гиперпараметры (скорость обучения, регуляризацию, архитектуру сети и т.п.), делаем ранний стоп. | Позволяет увидеть, как модель обобщает на unseen‑данные, не затрагивая окончательный тест. Это защищает от переобучения на train. |
| **Test (тестовая)** | Финальная unbiased оценка готового продукта: считаем метрики (accuracy, F1, RMSE и т.д.) один раз после того, как все решения приняты. | Дает честную оценку того, как модель будет работать в реальном мире, потому что она никогда не видела эти данные во время обучения и настройки. |

**2. Почему нельзя постоянно подбирать параметры по test**

Если мы будем менять гиперпараметры, пока не получим лучший результат на test, то test перестаёт быть независимым набором: он начинает влиять на процесс обучения. В результате:

- **Переобучение на test** – модель «запоминает» особенности именно этой выборки, а не общие закономерности.
- Оценка становится **оптимистически завышенной**; в реальномDeploy‑окружении модель покажет худшие метрики.
- Нарушается принцип **hold‑out**: тест должен оставаться untouched до самого конца эксперимента.

Поэтому test используют **только один раз** после окончательного выбора модели и всех настроек.

**3. Короткий практический пример**

Представим, что мы решаем задачу бинарной классификации спама/не‑спама.

1. **Делим данные** (например, 60 % train, 20 % validation, 20 % test).
2. **Обучаем** несколько моделей (логистическую регрессию, случайный лес, небольшую нейросеть) на train.
3. На validation измеряем AUC‑ROC для каждой модели и подбираем гиперпараметры (например, глубину деревьев в случайном лесе, коэффициент L2‑регуляризации в логистической регрессии). Выбираем модель с наилучшим validation‑AUC.
4. После финишного выбора **один раз** запускаем выбранную модель на test и получаем окончательный AUC = 0.93. Эта цифра теперь является честной оценкой того, как модель будет работать на новых письмах.

Если бы мы настраивали параметры, глядя на test, мы могли бы, например, подобрать порог классификации, который максимизирует accuracy именно на этом наборе, но в реальной почте accuracy упал бы до 0.78, потому что test уже не был независимым.

Таким образом, разделение на train/validation/test обеспечивает честную настройку модели и надежную оценку её обобщающей способности.

================================================================================
rag | gigachat
Time: 4.39 sec
Tokens: 1583
Length: 392 chars

Answer:

Хроническая бедность определяется длительностью пребывания в состоянии бедности. Основные характеристики включают:

- Длительность бедности (необходимое и достаточное условие);
- Многомерность (бедность проявляется в разных аспектах жизни);
- Тяжесть («ультрабедность»);
- Межпоколенная передача (интеграционное наследование бедности);
- Социальная гетерогенность группы хронических бедняков.

================================================================================
rag | openrouter_small
Time: 10.94 sec
Tokens: 2016
Length: 1705 chars

Answer:

В документе хроническая бедность определяется как бедность, которая **существует в течение длительного времени** – авторы считают, что длительность является необходимым и достаточным условием для того, чтобы бедность считалась хронической. Более узкое определение, которое они предлагают, – это **межпоколенческая (IGT) бедность**, которая передается через поколения и, как правило, является трудно поддающейся устранению, даже если она не является тяжелой.

**Выделенные характеристики хронической бедности:**

1. **Продолжительность** – бедность сохраняется в течение длительного периода времени.
2. **Многомерность** – хроническая бедность часто включает в себя несколько аспектов лишений (не только доход).
3. **Тяжесть** – хроническая бедность, как правило, является серьезной и может перерастать в «ультрабедность».
4. **Межпоколенческая передача** – бедность передается через поколения посредством передачи человеческого, социального, культурного, политического, финансового/материального и экологического/природного капитала.
5. **Гетерогенность** – хронически бедные составляют разнородную группу, в которую входят:
   - Люди, испытывающие лишения из-за своего жизненного этапа.
   - Лица, подвергающиеся дискриминации из-за своего социального положения в общине или домашнем хозяйстве.
   - Люди с проблемами здоровья и ограниченными возможностями.
   - Люди, живущие в отдаленных сельских районах, городских гетто и регионах, где происходили длительные вооруженные конфликты и нестабильность.

Эти характеристики – длительность, многомерность, тяжесть, межпоколенческая передача и гетерогенный состав – являются основными элементами, которые авторы используют для описания хронической бедности.

================================================================================
rag | openrouter_large
Time: 4.15 sec
Tokens: 1921
Length: 876 chars

Answer:

Хроническая бедность в документе определяется как бедность длительной продолжительности – длительность считается как необходимым, так и достаточным условием для отнесения бедности к хронической.

Авторы выделяют следующие характеристики хронической бедности:

- длительная продолжительность (основное условие);
- часто многомерность (бедность проявляется не только по доходу, но и в других измерениях);
- часто высокая степень тяжести (серьёзность);
- часто передаётся между поколениями (межпоколенческая передача бедности);
- гетерогенность группы хронически бедных (различные уязвимые категории: люди определённого этапа жизненного цикла, дискриминируемые социальные группы, лица с проблемами здоровья, жители отдалённых сельских районов, городских гетто и зон prolonged violent conflict).

Эти характеристики совместно описывают хроническую бедность в работе.

In [145]:
benchmark_df = pd.DataFrame(benchmark_results)
benchmark_df

,task,model,time_sec,answer_chars,prompt_tokens,completion_tokens,total_tokens
0,logic,gigachat,5.910866,379,79,111,190
1,logic,openrouter_small,4.302538,1046,75,632,707
2,logic,openrouter_large,11.327665,545,95,399,494
3,code,gigachat,8.606857,1332,70,335,405
4,code,openrouter_small,5.248955,1324,67,637,704
5,code,openrouter_large,3.215252,1726,88,638,726
6,analytic,gigachat,11.922416,2131,73,447,520
7,analytic,openrouter_small,10.393033,3195,66,998,1064
8,analytic,openrouter_large,9.300930,2671,87,839,926
9,rag,gigachat,4.393836,392,1494,89,1583
10,rag,openrouter_small,10.944278,1705,1362,654,2016
11,rag,openrouter_large,4.150766,876,1494,427,1921

### Предварительная оценка качества

Все три модели корректно справились с четырьмя основными задачами.

- **Логическая задача:** все модели дали правильное решение. GigaChat ответил наиболее кратко, OpenRouter-модели — более подробно и структурированно.
- **Генерация кода:** все три модели предложили корректную реализацию функции и правильно обработали дубликаты и случай с менее чем двумя уникальными значениями.
- **Аналитический ответ:** все модели правильно объяснили назначение train, validation и test. OpenRouter-модели дали более подробные ответы, GigaChat — более компактный.
- **RAG-вопрос:** все модели корректно использовали предоставленный контекст и выделили основные характеристики хронической бедности. Явных галлюцинаций не обнаружено.

По скорости результаты различаются от задачи к задаче. GigaChat не всегда был самым быстрым, а крупная OpenRouter-модель в отдельных задачах работала быстрее маленькой. Поэтому по четырём запросам делать общий вывод о скорости пока рано.

### Тест длинного контекста

Все модели получают одинаковый prompt объёмом более 1000 входных токенов.  
Проверяется способность обработать длинный контекст, а также фиксируются время ответа и использование токенов.

In [146]:
long_context = rag_text[:12000]

long_prompt = f"""
Ниже приведён фрагмент научного документа.

Прочитай его и кратко ответь на три вопроса:

1. Как авторы определяют хроническую бедность?
2. Какие основные характеристики хронической бедности они выделяют?
3. Какие подходы к анализу бедности упоминаются в документе?

Используй только информацию из приведённого текста.
Если какой-либо информации недостаточно, прямо скажи об этом.

Текст:
{long_context}
"""

Запуск на всех моделях:

In [147]:
long_prompt_results = []

for model_name in MODELS:
    print("\n" + "=" * 80)
    print(model_name)

    try:
        result = call_model(model_name, long_prompt, max_tokens=1000)

        long_prompt_results.append({
            "model": model_name,
            "time_sec": result["time_sec"],
            "answer_chars": len(result["text"]),
            "prompt_tokens": result["prompt_tokens"],
            "completion_tokens": result["completion_tokens"],
            "total_tokens": result["total_tokens"],
        })

        print("Time:", round(result["time_sec"], 2), "sec")
        print("Prompt tokens:", result["prompt_tokens"])
        print("Completion tokens:", result["completion_tokens"])
        print("Total tokens:", result["total_tokens"])
        print("\nAnswer:\n")
        print(result["text"])

    except Exception as e:
        print("ERROR:", repr(e))

================================================================================
gigachat
Time: 26.07 sec
Prompt tokens: 2854
Completion tokens: 621
Total tokens: 3475

Answer:

### Ответы на вопросы:

**1. Определение хронической бедности авторами:**
Авторы определяют хроническую бедность как состояние длительного пребывания человека или группы лиц в условиях бедности, часто начиная с рождения и продолжаясь всю жизнь. Хроническая бедность характеризуется длительностью, межпоколенной передачей, многоаспектностью проявлений и устойчивостью к существующим мерам борьбы с бедностью.

---

**2. Основные характеристики хронической бедности:**
Авторы выделяют несколько ключевых характеристик хронической бедности:
- **Длительность**: длительный срок нахождения в состоянии бедности является необходимым и достаточным условием отнесения бедности к хронической.
- **Многоаспектность (multi-dimensionality)**: хронически бедные испытывают нехватку ресурсов не только в денежном выражении, но и в социальных, культурных, политических, человеческих и природных ресурсах.
- **Интенсивность (severity)**: хроническая бедность обычно проявляется в крайней степени тяжести («ультрабедность»).
- **Межпоколенная передача (Intergenerational Transmission of Poverty, IGT)**: склонность бедности передаваться от поколения к поколению, делая её трудноустранимой.
- **Социальная неоднородность**: хронически бедные представляют собой разнородную группу населения, включающую уязвимых групп (дети, пожилые, женщины, жители отдалённых сельских районов, городские гетто, пострадавшие от конфликтов и насилия).

---

**3. Подходы к анализу бедности, упомянутые в тексте:**
Документ выделяет следующие подходы к анализу бедности:
- **Количественный подход (money-metric)** — измерение бедности через денежные показатели дохода, расходов и потребления.
- **Многомерный подход (multidimensional approach)** — оценка бедности по нескольким аспектам (доход, здоровье, образование, социальные связи и др.).
- **Подход абсолютной и относительной бедности** — различие между абсолютной линией бедности (недостаток базовых потребностей) и относительным уровнем бедности (социальное сравнение).
- **Оценка субъективной бедности** — восприятие бедности самими людьми.
- **Концепция свободы и возможностей (capability approach)** — бедность рассматривается как ограничение свобод и возможностей индивидов.
- **Анализ уязвимости (vulnerability analysis)** — изучение рисков и угроз, приводящих к бедности.
- **Анализ жизненных стратегий (livelihood analysis)** — выявление способов выживания и адаптации бедных домохозяйств.
- **Политический и социальный анализ исключения (social and political exclusion)** — рассмотрение влияния социальной стратификации и дискриминации на бедность.
- **Панельные количественные исследования (quantitative panel data analysis)** — отслеживание изменений состояния бедности во времени.
- **Разработка политики (policy analysis frameworks)** — разработка рекомендаций и мер по снижению хронической бедности.

---

Таким образом, документ охватывает широкий спектр подходов и характеристик хронической бедности, подчёркивая необходимость комплексного понимания проблемы и разработки дифференцированных методов её преодоления.

================================================================================
openrouter_small
Time: 13.42 sec
Prompt tokens: 2623
Completion tokens: 998
Total tokens: 3621

Answer:

**1. Как авторы определяют хроническую бедность?**
Авторы определяют хроническую бедность в первую очередь по её **продолжительности** – бедность считается хронической, если она длится **долго** (является необходимым и достаточным условием). В тексте также отмечается, что хроническая бедность может быть связана с бедностью **с рождения** и что наиболее строгое определение – это **межпоколенческая передача (IGT) бедности**.

**2. Какие основные характеристики хронической бедности они выделяют?**
В документе указаны следующие основные характеристики:

* **Продолжительность** – длительная (часто с рождения) бедность.
* **Серьёзность** – хроничесная бедность, как правило, является **серьёзной** (иногда называемой «ультрабедностью»).
* **Многомерность** – хроничесная бедность часто проявляется в **нескольких аспектах** (помимо дохода).
* **Межпоколенческая передача** – бедность, передающаяся через поколения, рассматривается как характерная черта (и причина) хронической бедности.
* **Гетерогенность** – хроничесно бедные составляют **разнообразную группу**, включая людей, страдающих от лишения по причине возраста, дискриминации, проблем со здоровьем, проживания в удалённых или конфликтных районах и т. п.

**3. Какие подходы к анализу бедности упоминаются в документе?**
В тексте приводится несколько подходов к анализу бедности (как общего, так и специфичного для хронической бедности):

* **Денежно-стоимостные (количественные) показатели** и другие количественные индикаторы.
* **Абсолютная и относительная бедность**.
* **Субъективные оценки бедности** (точка зрения самих бедных).
* **Подход, основанный на возможностях и свободе**.
* **Подход, основанный на уязвимости**.
* **Социальная и политическая изоляция**.
* **Аналитические рамки** для хронической бедности, перечисленные в разделе 4:
  * Количественный анализ панельных данных.
  * Анализ средств к существованию (жизненных ресурсов).
  * Анализ свобод.
  * Анализ социальной изоляции.
  * Рамки анализа политики, направленные на предотвращение негативных последствий развития, которые у

================================================================================
openrouter_large
Time: 5.74 sec
Prompt tokens: 2839
Completion tokens: 1000
Total tokens: 3839

Answer:

1. **Определение хронической бедности**
   Авторы считают, что хроническая бедность определяется прежде всего **длительностью** – длительная бедность является как необходимым, так и достаточным условием для её отнесения к хронической. При этом хроническая бедность, как правило, многомерна и тяжела, может передаваться между поколениями (межпоколенческая передача бедности, IGT) и понимается через призму абсолютной и относительной бедности, уязвимости, социального исключения, возможностей и свобод, а также субъективных оценок самих бедных.

2. **Основные характеристики хронической бедности**
   - **Длительность** (долгосрочная бедность).
   - **Многомерность** (бедность проявляется не только в доходе, но и в других измерениях – здоровье, образование, социальные связи и т.д.).
   - **Тяжесть/серьёзность** (часто связана с ультрабедностью).
   - **Межпоколенческая передача** (IGT бедность) – считается как характеристикой, так и причиной хронической бедности.
   - **Гетерогенность** группы хронически бедных (различные уязвимые категории: люди определённого этапа жизненного цикла, дискриминируемые социальные группы, лица с проблемами здоровья, жители удалённых сельских районов, городских ghetto и регионов с длительным конфликтом).
   - Возможная классификация по продолжительности: всегда бедные, обычно бедные, « churning » бедные (часто меняющие статус),occasionally бедные, никогда не бедные.

3. **Подходы к анализу бедности, упомянутые в документе**
   - **Материальные и денежные показатели** (income/expenditure/consumption) – традиционные количественные методы.
   - **Многомерные концепции бедности** (помимо дохода).
   - **Абсолютная и относительная бедность**.
   - **Субъективные оценки бедности** (оценки самих бедных).
   - **Подход возможностей и свобод** (capabilities and freedoms).
   - **Уязвимость** (vulnerability).
   - **Аналитические рамки для изучения хронической бедности**:
     * количественный панельный анализ данных;
     * анализ средств к существованию (livelihoods analysis);
     *

In [148]:
long_prompt_df = pd.DataFrame(long_prompt_results)
long_prompt_df

,model,time_sec,answer_chars,prompt_tokens,completion_tokens,total_tokens
0,gigachat,26.074792,3055,2854,621,3475
1,openrouter_small,13.419111,2064,2623,998,3621
2,openrouter_large,5.743514,2064,2839,1000,3839

### Вывод по длинному prompt

Все три модели успешно обработали входной контекст объёмом более 2500 токенов.

В данном тесте самой быстрой оказалась крупная модель OpenRouter, затем малая модель OpenRouter и GigaChat.

При этом обе модели OpenRouter достигли установленного лимита `max_tokens=1000`, поэтому их ответы были частично обрезаны. GigaChat завершил ответ самостоятельно и не исчерпал лимит генерации.

Таким образом, ограничений по размеру контекста в рамках данного эксперимента не обнаружено, но при длинных ответах необходимо учитывать лимит `max_tokens`.

### Нагрузочный тест

Для каждой модели выполняется 10 последовательных коротких запросов.  
Фиксируются успешность запросов, среднее время ответа и возникающие ошибки API.

In [149]:
load_test_prompt = "Одним предложением объясни, что такое векторная база данных."

In [150]:
def run_load_test(model_name, n_requests=10):
    times = []
    errors = []

    for i in range(n_requests):
        try:
            result = call_model(model_name, load_test_prompt, max_tokens=300)

            times.append(result["time_sec"])

            print(
                f"{i + 1}/{n_requests}:",
                f"{result['time_sec']:.2f} sec"
            )

        except Exception as e:
            errors.append(repr(e))

            print(
                f"{i + 1}/{n_requests}: ERROR",
                repr(e)
            )

    return {
        "model": model_name,
        "requests": n_requests,
        "successful": len(times),
        "errors": len(errors),
        "avg_time_sec": np.mean(times) if times else None,
        "min_time_sec": np.min(times) if times else None,
        "max_time_sec": np.max(times) if times else None,
        "error_messages": errors,
    }

In [151]:
load_test_results = []

for model_name in MODELS:
    print("\n" + "=" * 80)
    print(model_name)

    result = run_load_test(model_name, n_requests=10)

    load_test_results.append(result)

================================================================================
gigachat
1/10: 2.80 sec
2/10: 3.62 sec
3/10: 1.24 sec
4/10: 1.41 sec
5/10: 0.95 sec
6/10: 1.08 sec
7/10: 1.29 sec
8/10: 5.11 sec
9/10: 2.39 sec
10/10: 1.16 sec

================================================================================
openrouter_small
1/10: 3.49 sec
2/10: 1.81 sec
3/10: 1.01 sec
4/10: 2.33 sec
5/10: 2.18 sec
6/10: 0.80 sec
7/10: 0.80 sec
8/10: 0.99 sec
9/10: 1.13 sec
10/10: 1.69 sec

================================================================================
openrouter_large
1/10: 1.69 sec
2/10: 1.62 sec
3/10: 23.97 sec
4/10: 3.48 sec
5/10: 3.22 sec
6/10: 2.48 sec
7/10: 24.68 sec
8/10: 1.12 sec
9/10: 2.41 sec
10/10: 1.16 sec

In [152]:
load_test_df = pd.DataFrame([
    {
        k: v
        for k, v in result.items()
        if k != "error_messages"
    }
    for result in load_test_results
])

load_test_df

,model,requests,successful,errors,avg_time_sec,min_time_sec,max_time_sec
0,gigachat,10,10,0,2.105180,0.954338,5.110277
1,openrouter_small,10,10,0,1.621438,0.795209,3.491048
2,openrouter_large,10,10,0,6.582635,1.123444,24.679016

### Итоговое сравнение моделей

| Критерий | GigaChat | OpenRouter small | OpenRouter large |
|---|---:|---:|---:|
| Логика | корректно | корректно | корректно |
| Генерация кода | корректно | корректно | корректно |
| Аналитический ответ | корректно | корректно | корректно |
| RAG | корректно | корректно | корректно |
| Явные галлюцинации | не обнаружены | не обнаружены | не обнаружены |
| Средняя задержка в нагрузочном тесте | 2.11 с | 1.62 с | 6.58 с |
| Минимальная задержка | 0.95 с | 0.80 с | 1.12 с |
| Максимальная задержка | 5.11 с | 3.49 с | 24.68 с |
| Успешных запросов | 10/10 | 10/10 | 10/10 |
| Long prompt 1000+ токенов | успешно | успешно | успешно |
| Удобство интеграции | хорошее | высокое | высокое |
| Стоимость в эксперименте | бесплатно по доступной квоте | бесплатно | бесплатно |
| Стабильность API | высокая | средняя | средняя |

### Вывод

Все три модели успешно справились с логической задачей, генерацией кода, аналитическим вопросом и RAG-вопросом по документу. Существенных ошибок или явных галлюцинаций в основных тестах не обнаружено.

GigaChat показал стабильную работу и обычно давал более компактные ответы. Интеграция через отдельный SDK немного специфичнее, чем у OpenRouter, но API в эксперименте работал стабильно.

OpenRouter удобен тем, что через единый OpenAI-совместимый интерфейс позволяет быстро переключаться между большим числом моделей. Это особенно удобно для экспериментов и выбора модели под конкретную задачу. При этом бесплатные модели оказались менее предсказуемыми по доступности: в ходе настройки встречались невалидные или снятые free-endpoint'ы, а также временные ошибки `429`.

Малая модель OpenRouter в нагрузочном тесте показала наименьшую среднюю задержку. Крупная модель также показала хорошее качество, но её время ответа было заметно менее стабильным.

На длинном prompt все модели успешно обработали контекст более 2500 токенов. Ограничений по длине контекста в рамках проведённого эксперимента не обнаружено, хотя OpenRouter-модели достигли установленного лимита генерации `max_tokens=1000`.

Для задач, где важны стабильность API, русскоязычные ответы и предсказуемая интеграция, GigaChat выглядит удобным вариантом. OpenRouter выгоднее, когда требуется доступ к разным моделям через единый интерфейс и возможность быстро сравнивать их между собой.

Локальный запуск оправдан, если важны конфиденциальность, отсутствие внешних API-зависимостей и полный контроль над моделью. Для небольших экспериментов и нерегулярных запросов API обычно проще, так как не требует собственной инфраструктуры и вычислительных ресурсов.

В данном эксперименте GigaChat использовался в рамках доступной квоты, а модели OpenRouter — через бесплатные endpoints, поэтому фактических денежных затрат не было.